'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto');
function load(file,stubs,extra={}){const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{module,exports:module.exports,require:id=>Object.hasOwn(stubs,id)?stubs[id]:require(id),console,process,...extra},{filename:file});return module.exports;}
function memory(){const values=new Map(),hash=new Map(),sets=new Map();let collision=false;return {values,hash,sets,collide(){collision=true;},async redis(cmds){return cmds.map(c=>{const [op,k,...args]=c;if(op==='GET')return values.get(k)||null;if(op==='HGET')return (hash.get(k)||{})[args[0]]||null;if(op==='SET'){if(args.includes('NX')&&values.has(k))return null;values.set(k,args[0]);return 'OK';}if(op==='ZREVRANGE'){return [...(sets.get(k)||new Map()).entries()].sort((a,b)=>b[1]-a[1]).slice(Number(args[0]),Number(args[1])+1).map(x=>x[0]);}if(op==='EVAL'){const n=Number(args[0]),keys=args.slice(1,1+n),argv=args.slice(1+n);if(k.includes("local old=")){const h=hash.get(keys[0])||{};h[argv[0]]=Math.max(Number(h[argv[0]]||0),Number(argv[1]));hash.set(keys[0],h);return 1;}if(collision){collision=false;const t=JSON.parse(values.get(keys[0]));t.replies.push({id:'b'.repeat(24),text:'Concurrent answer',authorId:'ID2',coach:false,createdAt:new Date().toISOString()});t.version++;values.set(keys[0],JSON.stringify(t));return 0;}if((values.get(keys[0])||'')!==argv[0])return 0;values.set(keys[0],argv[1]);keys.slice(1).forEach(key=>{const z=sets.get(key)||new Map();z.set(argv[3],Number(argv[2]));sets.set(key,z);});return 1;}throw new Error('Unexpected '+op);});}};}
function reviewModule(mem){return load('lib/club-reviews.js',{'./club-social':{redis:mem.redis,clean:(s,max)=>String(s==null?'':s).trim().slice(0,max)},crypto});}
const actor={accountId:'ID1',name:'Игрок',coach:false,admin:false};
const body={requestId:'a'.repeat(24),title:'Как сыграть?',question:'Колл или пас на тёрне?',type:'hand',forCoach:true};
function response(){return {statusCode:200,setHeader(){},status(n){this.statusCode=n;return this;},json(b){this.body=b;return this;},end(){}};}
test('creation is idempotent; forged author/coach fields do not override server identity',async()=>{const mem=memory(),m=reviewModule(mem);const first=await m.create({...body,authorId:'ID9',coach:true},actor);const second=await m.create(body,actor);assert.equal(first.thread.authorId,'ID1');assert.equal(second.thread.id,first.thread.id);assert.equal(second.fresh,false);const r=m.reply(first.thread,{text:'Мой ответ',requestId:'c'.repeat(24),coach:true},actor);assert.equal(r.reply.coach,false);assert.equal(first.thread.version,1);assert.equal(m.reply(first.thread,{text:'Мой ответ',requestId:'c'.repeat(24)},actor).fresh,false);});
test('CAS retries preserve a concurrent reply instead of overwriting it',async()=>{const mem=memory(),m=reviewModule(mem),{thread}=await m.create(body,actor);mem.collide();const result=await m.mutate(thread.id,t=>m.reply(t,{text:'Другой ответ',requestId:'d'.repeat(24)},actor));assert.equal(result.thread.replies.length,2);assert.equal(result.thread.version,2);});
test('read receipts acknowledge only the shown version, never future answers or regressions',async()=>{const mem=memory(),m=reviewModule(mem),{thread}=await m.create(body,actor);await m.mutate(thread.id,t=>m.reply(t,{text:'Ответ номер один',requestId:'c'.repeat(24)},{...actor,accountId:'ID2'}));await m.markRead(thread.id,'ID1',1);await m.mutate(thread.id,t=>m.reply(t,{text:'Ответ номер два',requestId:'d'.repeat(24)},{...actor,accountId:'ID2'}));assert.equal((await m.list(actor,true)).threads[0].unread,true);await m.markRead(thread.id,'ID1',999);await m.markRead(thread.id,'ID1',0);assert.equal((await m.list(actor,true)).threads[0].unread,false);});
test('invalid images, absent parents and empty questions are rejected',()=>{const m=reviewModule(memory());assert.throws(()=>m.newThread({...body,question:''},actor,'a'),/вопрос/);assert.throws(()=>m.image('https://example.com/image'),/изображение/);assert.throws(()=>m.image('data:image/svg+xml;base64,abcd'),/изображение/);const t=m.newThread(body,actor,'a');assert.throws(()=>m.reply(t,{text:'Ответ',parentId:'missing',requestId:'c'.repeat(24)},actor),/удалён/);});
test('public cards conceal subscriber identities and other voters',()=>{const m=reviewModule(memory()),t=m.newThread(body,actor,'a');t.followers.ID2=true;t.votes.ID2='fold';const p=m.publicThread(t,actor);assert.equal(p.followers,undefined);assert.equal(p.votes.ID2,undefined);assert.equal(p.votes.fold,1);});
test('handler prevents foreign deletion, stamps coach from resolved account and sends to subscribers',async()=>{const mem=memory(),m=reviewModule(mem);const {thread}=await m.create(body,actor);let who='ID2',sent=[];const h=load('lib/api-handlers/club-reviews.js',{'../club-social':{context:async req=>({body:req.body,accountId:who,admin:false}),memberProfile:async()=>({name:'Игрок'}),coachAccount:async()=> 'ID3'},'../club-reviews':m,'../chat-webpush-notify':{sendToMemberDevices:async(id,p)=>{sent.push({id,p});}}});let res=response();await h({body:{action:'delete',id:thread.id}},res);assert.equal(res.statusCode,403);res=response();await h({body:{action:'reply',id:thread.id,text:'Мнение игрока',coach:true,requestId:'e'.repeat(24)}},res);assert.equal(res.body.thread.replies[0].coach,false);who='ID3';res=response();await h({body:{action:'reply',id:thread.id,text:'Разбор тренера',requestId:'f'.repeat(24)}},res);assert.equal(res.body.thread.replies[1].coach,true);assert.equal(sent.length,2);assert.ok(sent.every(x=>x.id==='ID1'));who='ID2';res=response();await h({body:{action:'delete-reply',id:thread.id,replyId:res.body?.thread?.replies?.[1]?.id|| (await m.read(thread.id)).replies[1].id}},res);assert.equal(res.statusCode,403);});
test('appearance only accepts earned catalog awards and known frame IDs',()=>{const m=load('lib/profile-appearance.js',{'./club-social':{},'./profile-achievement-catalog.json':{}});const awards=m.earned('Waaar',{'waaar':{first:1,total:999999,heroes:0,big50:1}});assert.equal(awards.some(x=>x.id==='millionaire'),false);assert.throws(()=>m.validate({frame:'gold',achievement:'millionaire'},awards),/не получена/);assert.throws(()=>m.validate({frame:'url(javascript:1)'},awards),/рамка/);assert.equal(m.validate({frame:'emerald',achievement:'tournament-king'},awards).achievement,'tournament-king');assert.equal(m.nickKey('Waaaarr'),'waaar');});
test('appearance writes are always scoped to authenticated account',async()=>{let written;const h=load('lib/api-handlers/profile-appearance.js',{'../club-social':{context:async req=>({body:req.body,accountId:'ID1'}),redis:async cmds=>{written=cmds;return ['OK'];}},'../account-id':{resolveAccountId:async id=>id},'../profile-appearance':{readAppearance:async id=>({accountId:id,achievements:[],frames:[]}),validate:()=>({frame:'gold',achievement:''})}});const res=response();await h({body:{action:'save',targetId:'ID2'}},res);assert.equal(res.statusCode,200);assert.equal(written[0][1],'poker_app:profile_appearance:ID1');});
test('trainer identity is pinned from verified binding, never a user display name',async()=>{const mem=memory();mem.hash.set('reverse',{fishkopcheny:'ID3'});mem.hash.set('profiles',{ID3:JSON.stringify({nickname:'FishKopcheny'})});mem.hash.set('bind',{ID3:'poker-player'});const m=load('lib/club-social.js',{'./redis':{pipeline:async cmds=>(await mem.redis(cmds)).map(result=>({result})),isConfigured:()=>true},'./resolve-telegram-auth':{},'./api-handlers/friends':{},'./app-user-blocks':{},'./api-auth':{},'./api-limits':{},'./pokerplus':{PROFILE_HASH_KEY:'profiles',BIND_HASH_KEY:'bind',NICKNAME_REVERSE_HASH_KEY:'reverse'}});assert.equal(await m.coachAccount(),'ID3');mem.hash.set('reverse',{fishkopcheny:'ID9'});assert.equal(await m.coachAccount(),'ID3');});
test('shared API gate requires a real signed-in account and rejects blocked users and null bodies',async()=>{let identity=null,blocked=false;const m=load('lib/club-social.js',{'./redis':{pipeline:async()=>[],isConfigured:()=>true},'./resolve-telegram-auth':{resolveTelegramIdentity:()=>identity,memberIdFromIdentity:who=>who.id},'./api-handlers/friends':{resolveNewsAccountId:async()=> 'ID1'},'./app-user-blocks':{rejectBlockedAppUser:async(req,res)=>{if(blocked)res.status(403).json({ok:false});return blocked;}},'./api-auth':{setCors(){},isAdminIdentity:()=>false},'./api-limits':{rejectIfPayloadTooLarge:()=>false,rateLimit:()=>false},'./pokerplus':{}});let res=response();assert.equal(await m.context({method:'POST',body:{}},res,'test'),null);assert.equal(res.statusCode,401);identity={id:'guest_fake'};res=response();await m.context({method:'POST',body:{}},res,'test');assert.equal(res.statusCode,401);identity={id:'tg_1'};blocked=true;res=response();await m.context({method:'POST',body:{}},res,'test');assert.equal(res.statusCode,403);blocked=false;res=response();await m.context({method:'POST',body:'null'},res,'test');assert.equal(res.statusCode,400);res=response();const c=await m.context({method:'POST',body:{accountId:'ID9'}},res,'test');assert.equal(c.accountId,'ID1');});
