const test=require('node:test'),assert=require('node:assert/strict'),T=require('../app-last-buy-in-tanks-engine.js'),C=require('../app-last-buy-in-chapters.js'),E=require('../app-last-buy-in-campaign-engine.js');
function clear(s){s.grid.forEach(r=>r.fill(0));s.spawnTick=99999;s.player.shield=0;}
function shot(x,y,dir=0,power=1,enemy=false){return {x,y,dir,power,enemy,speed:.23,owner:{}};}
test('Alena replaces the carpet chapter, campaign delegates simulation',()=>{assert.equal(C.length,12);assert.equal(C[6].hero,'alena');assert.equal(E.create(6).mode,'tanks');const s=E.create(6);E.step(s,{left:true});assert.ok(s.player.x<9);});
test('brick quarters break, steel requires three stars, water passes shells',()=>{const s=T.create();clear(s);s.grid[9][5]=1;s.grid[9][6]=1;assert.equal(T.bulletStep(s,shot(6,10.1)),false);assert.equal(s.grid[9][5]+s.grid[9][6],0);s.grid[9][6]=2;T.bulletStep(s,shot(6.2,10.1));assert.equal(s.grid[9][6],2);T.bulletStep(s,shot(6.2,10.1,0,2));assert.equal(s.grid[9][6],0);s.grid[9][6]=3;assert.equal(T.bulletStep(s,shot(6.2,10.1)),true);assert.equal(T.fits(s,{},6,10),false);});
test('shells cancel each other and armor takes four hits',()=>{const s=T.create();clear(s);const t={x:6,y:9,type:3,hp:4,spawnShield:0};s.enemies.push(t);for(let i=0;i<4;i++)T.bulletStep(s,shot(6,10));assert.equal(s.killed,1);assert.equal(s.enemies.length,0);const a=shot(7,7,1),b=shot(7.2,7,3,1,true);s.shots=[a,b];assert.equal(T.bulletStep(s,a),false);assert.ok(b.dead);});
test('tank loss respawns shielded; headquarters loss restarts current quarter',()=>{const s=T.create();clear(s);s.killed=7;s.player.x=6;s.player.y=9;T.bulletStep(s,shot(6,10,0,1,true));assert.ok(s.lost);T.revive(s);assert.equal(s.killed,7);assert.equal(s.player.shield,180);s.player.x=1;s.player.y=1;T.bulletStep(s,shot(13,23.9,2,1,true));assert.ok(s.lost);assert.equal(s.hqAlive,false);T.revive(s);assert.equal(s.killed,0);assert.equal(s.hqAlive,true);});
test('all six bonuses have their authentic distinct effects',()=>{const s=T.create();clear(s);for(let i=0;i<3;i++)T.collect(s,{type:'star'});assert.equal(s.player.star,3);T.collect(s,{type:'helmet'});assert.equal(s.player.shield,600);T.collect(s,{type:'timer'});assert.equal(s.freeze,600);T.collect(s,{type:'shovel'});assert.equal(s.grid[23][12],2);T.collect(s,{type:'life'});assert.equal(s.extraLives,1);s.enemies=[{x:6,y:6,type:0},{x:8,y:8,type:3}];T.collect(s,{type:'grenade'});assert.equal(s.enemies.length,0);assert.equal(s.killed,2);});
test('three quarters require twenty defeated tanks each, then campaign victory',()=>{const s=T.create();for(let round=1;round<=3;round++){clear(s);s.spawned=20;for(let n=0;n<20;n++){const t={x:6,y:9,type:n%4,hp:n%4===3?4:1,spawnShield:0};s.enemies.push(t);while(s.enemies.includes(t))T.bulletStep(s,shot(6,10));}T.step(s);assert.equal(s.killed,20);for(let i=0;i<150;i++)T.step(s);if(round<3)assert.equal(s.round,round+1);}assert.equal(s.won,true);assert.equal(s.picked,60);});
test('enemy tank AI advances, shoots, and frozen tanks stop completely',()=>{const s=T.create();for(let i=0;i<400;i++)T.step(s);assert.ok(s.enemies.length>0);const t=s.enemies[0];assert.ok(t.y>1);s.freeze=120;const x=t.x,y=t.y;for(let i=0;i<60;i++)T.step(s);assert.equal(t.x,x);assert.equal(t.y,y);s.freeze=0;t.cooldown=0;T.step(s);assert.ok(s.shots.some(b=>b.enemy));});
test('upgrades allow two simultaneous shells and survive a completed quarter',()=>{const s=T.create();clear(s);s.player.star=2;T.fire(s,s.player);s.player.cooldown=0;T.fire(s,s.player);s.player.cooldown=0;T.fire(s,s.player);assert.equal(s.shots.length,2);s.killed=20;s.spawned=20;T.step(s);for(let i=0;i<150;i++)T.step(s);assert.equal(s.round,2);assert.equal(s.player.star,2);});
test('tank movement respects water and masonry; ice carries release momentum',()=>{const s=T.create();clear(s);s.player.x=5;s.player.y=8;s.grid[6][4]=s.grid[6][5]=1;for(let i=0;i<30;i++)T.step(s,{up:true});assert.ok(s.player.y>=7.77);s.grid.forEach(r=>r.fill(5));s.player.x=9;s.player.y=20;T.step(s,{right:true});const x=s.player.x;T.step(s,{});assert.ok(s.player.x>x);s.grid.forEach(r=>r.fill(0));T.step(s,{});assert.equal(s.player.vx,0);});
