const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-campaign-engine.js');
function play(s){const {controller}=require('./helpers/last-buy-in-campaign-player.cjs');let frames=0;for(;frames<6000&&!s.won&&!s.lost;frames++)E.step(s,controller(s));return {frames};}
test('all three relays can be completed from normal spawn with ordinary inputs',()=>{const s=E.create(10),r=play(s);assert.equal(s.won,true);assert.equal(s.puzzles,3);assert.ok(s.hits<=2);assert.ok(r.frames<3000);console.log('Portal walkthrough:',r.frames,'frames /',(r.frames/60).toFixed(1),'s,',s.hits,'hits');});
test('every relay fits on one screen and hazards increase gradually',()=>{const s=E.create(10);assert.equal(s.portalGuards.length,0);for(const p of s.platforms)assert.ok(p.x>=0&&p.x+p.w<=390);assert.ok(s.cube.x<s.portals[0].x&&s.pad.x>s.portals[1].x);assert.equal(s.panel.hp,0);});
test('entry requires a carried cell and cannot be reversed by accident',()=>{const s=E.create(10);s.x=s.portals[0].x;s.y=465;s.ground=true;E.step(s,{});assert.equal(s.crossedPortal,false);const pair=s.portals.map(p=>p.x);E.step(s,{resetPortal:true});assert.deepEqual(s.portals.map(p=>p.x),pair);assert.equal(s.puzzles,0);});
test('reset restores only the current relay and costs no health or completed progress',()=>{const s=E.create(10);s.puzzles=2;E.step(s,{resetPortal:true});assert.equal(s.puzzles,2);assert.equal(s.portalGuards.length,2);assert.equal(s.x,828);const health=s.health;s.carry=true;E.step(s,{});E.step(s,{resetPortal:true});assert.equal(s.puzzles,2);assert.equal(s.health,health);assert.equal(s.carry,false);assert.equal(s.cube.x,892);assert.equal(s.portalClock,0);});
test('a misplaced cell can be picked up again and cannot activate receiver remotely',()=>{const s=E.create(10);s.x=s.cube.x;E.step(s,{attack:true});assert.equal(s.carry,true);E.step(s,{});E.step(s,{attack:true});assert.equal(s.portalCharge,0);E.step(s,{});E.step(s,{attack:true});assert.equal(s.carry,true);});
test('dropped cells outside the room return to the dock',()=>{const s=E.create(10);s.cube.x=400;s.cube.y=560;E.step(s,{});assert.equal(s.cube.x,112);assert.equal(s.cube.y,465);assert.equal(s.lost,false);});
test('laser warns first, hurts at ground level and allows a jump above the beam',()=>{
 for(const y of [465,360]){const s=E.create(10);s.puzzles=1;E.step(s,{resetPortal:true});s.inv=0;const g=s.portalGuards[0];s.portalRoomTick=19;s.x=g.x;s.y=y;s.ground=y===465;E.step(s,{});assert.equal(g.warning,true);assert.equal(g.active,false);assert.equal(s.health,5);s.portalRoomTick=59;s.x=g.x;s.y=y;s.vy=0;E.step(s,{});assert.equal(g.active,true);assert.equal(s.health,y===465?4:5);}
});
test('unpowered portal requires a nearby console, not a remote action or carried cell alone',()=>{const s=E.create(10);s.puzzles=1;E.step(s,{resetPortal:true});assert.equal(s.portalPowered,false);E.step(s,{});E.step(s,{special:true});assert.equal(s.portalPowered,false);s.x=s.portalConsole.x;s.y=465;s.ground=true;E.step(s,{});E.step(s,{special:true});assert.equal(s.portalPowered,true);assert.equal(s.carry,false);});
test('final upper route has a real jump gap and a raised receiver',()=>{const s=E.create(10);s.puzzles=2;E.step(s,{resetPortal:true});const upper=s.platforms.slice(1);assert.equal(upper.length,2);assert.ok(upper[1].x>upper[0].x+upper[0].w);assert.ok(upper[1].y<upper[0].y);assert.equal(s.pad.y,upper[1].y);assert.ok(s.portals[1].x<upper[0].x+upper[0].w);});
