const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-engine'),{controller}=require('./helpers/last-buy-in-player.cjs');
test('every chapter can be completed through ordinary controls and boss encounters',()=>{for(let chapter=1;chapter<7;chapter++){const s=E.create(chapter);let sawBoss=false,sawDuel=false;while(!s.won&&!s.lost&&s.tick<18000){const a=controller(s);if(a.bet)E.choose(s,a.bet);E.step(s,a);sawBoss ||=s.phase==='boss';sawDuel ||=s.phase==='duel';assert.ok(Number.isFinite(s.x)&&Number.isFinite(s.y));}assert.ok(s.won,JSON.stringify({chapter,hp:s.health,tick:s.tick}));assert.equal(s.boss.hp,0);assert.equal(sawBoss,true);if(chapter===5)assert.equal(sawDuel,true);const tick=s.tick;E.step(s,{attack:true});assert.equal(s.tick,tick);}});
test('poker decisions require three correct answers and the operation timer expires',()=>{const s=E.create(5);s.phase='duel';s.hand=0;assert.equal(E.choose(s,'raise'),false);assert.equal(s.hand,0);assert.equal(E.choose(s,'fold'),true);assert.equal(E.choose(s,'call'),true);assert.equal(E.choose(s,'raise'),true);assert.equal(s.phase,'boss');const expiry=E.create(5);expiry.timer=1;E.step(expiry,{});assert.equal(expiry.lost,true);});

test('bosses follow full-length routes rather than introductory encounters',()=>{for(const chapter of [1,2,3,4,5]){const s=E.create(chapter);while(!s.won&&!s.lost&&s.phase!=='boss'&&s.tick<18000){const a=controller(s);if(a.bet)E.choose(s,a.bet);E.step(s,a);}assert.equal(s.phase,'boss');if(chapter===1)assert.equal(s.wave,7);if(chapter===2)assert.ok(s.x>5600);if(chapter===3)assert.equal(s.picked,7);if(chapter===4)assert.ok(s.progress>=70);if(chapter===5)assert.equal(s.room,7);assert.ok(s.intensity>=.8);}});

test('Roma stays on the floor and his ATM attacks work at range',()=>{const s=E.create(1);for(let i=0;i<120;i++)E.step(s,{up:true,left:true});assert.equal(s.y,270);assert.equal(s.x,30);s.enemies=[{x:280,y:400,hp:4,type:0,timer:70,stun:0}];s.x=60;s.y=400;for(let i=0;i<40;i++)E.step(s,{attack:true});assert.ok(s.enemies[0].hp<4);assert.equal(s.hits,0);E.step(s,{special:true});assert.equal(s.cashTraps.length,1);const trap=s.cashTraps[0];s.enemies[0].x=trap.x+10;s.enemies[0].y=trap.y;s.enemies[0].stun=0;E.step(s,{});assert.ok(s.enemies[0].stun>0);assert.equal(trap.life,0);});

test('120 thousand fires shield-piercing notes and recharges after 60 seconds',()=>{const s=E.createBoss(1);E.step(s,{super:true});assert.equal(s.superCooldown,3600);assert.ok(s.shots.some(p=>p.kind==='supernote'));E.step(s,{super:true});assert.equal(s.superCooldown,3599);const hp=s.enemies.reduce((n,e)=>n+e.hp,0);for(let i=0;i<40;i++)E.step(s,{});assert.ok(s.enemies.reduce((n,e)=>n+e.hp,0)<hp);const recharge=E.create(1);recharge.superCooldown=3600;recharge.enemies=[];recharge.wave=1;for(let i=0;i<3600;i++){recharge.inv=2;E.step(recharge,{});}assert.equal(recharge.superCooldown,0);});
