const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-campaign-engine');
test('three distinct tracks stay inside the phone playfield with increasing pressure',()=>{const signatures=[];for(let wave=1;wave<=3;wave++){const path=E.zumaPath(wave);assert.ok(path.length>1050);assert.ok(path.points.every(p=>p.x>=20&&p.x<=370&&p.y>=80&&p.y<=412));signatures.push(JSON.stringify(E.zumaPoint(wave,500)));}assert.equal(new Set(signatures).size,3);const s=E.create(3),stages=[];const {controller}=require('./helpers/last-buy-in-campaign-player.cjs');while(!s.won&&s.tick<20000){if(!stages.some(v=>v.wave===s.wave))stages.push({wave:s.wave,speed:s.zumaSpeed,colors:s.colorCount});E.step(s,controller(s));assert.equal(s.lost,false);}assert.equal(s.won,true);assert.equal(stages.length,2);assert.ok(stages[0].speed<stages[1].speed);assert.equal(stages[1].colors,5);});
test('shots travel before insertion, matches fade and surviving chips close the gap smoothly',()=>{const s=E.create(3);s.reserve=0;s.chain=[0,0,1,1].map((color,i)=>({color,displayDistance:i*24}));s.ball=0;s.nextBall=1;E.step(s,{aim:1,attack:true});assert.ok(s.zumaShot);assert.equal(s.chain.length,4);assert.equal(s.score,0);const initialY=s.zumaShot.y;E.step(s,{});assert.notEqual(s.zumaShot.y,initialY);while(s.zumaShot)E.step(s,{});assert.deepEqual(s.chain.map(c=>c.color),[1,1]);assert.equal(s.zumaEffects.length,3);assert.equal(s.score,90);const before=s.chain[0].displayDistance;E.step(s,{});assert.ok(s.chain[0].displayDistance<before);assert.ok(s.chain[0].displayDistance>s.travel);for(let i=0;i<25;i++)E.step(s,{});assert.equal(s.zumaEffects.length,0);});
test('stage changes wait for the fade and a pause instead of replacing the scene instantly',()=>{const s=E.create(3);s.chain=[];s.reserve=0;s.zumaEffects=[{life:12,maxLife:24}];for(let i=0;i<10;i++)E.step(s,{});assert.equal(s.stagePause,0);assert.equal(s.wave,1);for(let i=0;i<2;i++)E.step(s,{});assert.equal(s.stagePause,90);assert.equal(s.wave,1);for(let i=0;i<90;i++)E.step(s,{});assert.equal(s.wave,3);assert.ok(s.chain.length>0);});

test('Emil follows Vaar; Roboshapka leads to Pavel and warns before a real speed burst',()=>{const C=require('../app-last-buy-in-chapters');assert.equal(C[2].hero,'vaar');assert.equal(C[3].hero,'emil');assert.equal(C[3].mode,'zuma');assert.ok(!C.some(c=>c.mode==='poker'));assert.match(C[2].after,/Эмил/);const s=E.create(3);assert.equal(s.boss.name,'Робошапка');s.stageTick=299;E.step(s,{});assert.equal(s.boss.warning,true);s.stageTick=344;const before=s.travel;E.step(s,{});assert.equal(s.boss.rush,true);assert.ok(s.travel-before>s.zumaSpeed*s.balance.pressure);const p=E.create(3,{bossOnly:true});assert.equal(p.wave,3);assert.equal(p.boss.name,'Павел Тертычный');const r=E.create(3,{bossOnly:true,preBoss:true});assert.equal(r.wave,1);assert.equal(r.boss.name,'Робошапка');});
test('boss health changes only after matching chips and overflow loses the round',()=>{const s=E.create(3,{bossOnly:true});s.reserve=0;const hp=s.boss.hp;for(let n=0;n<30;n++)E.step(s,{});assert.equal(s.boss.hp,hp);s.travel=E.zumaPath(3).length-(s.chain.length-1)*24+1;const before=s.chain[0].displayDistance;E.step(s,{});assert.ok(s.lost);assert.ok(Math.abs(s.chain[0].displayDistance-before)<400);assert.notEqual(s.chain[0].displayDistance,0);assert.equal(s.boss.hp,hp);});
test('matching bonus chips triggers bomb, slow and reverse',()=>{for(const bonus of ['bomb','slow','back']){const s=E.create(3);s.reserve=0;s.chain=[1,0,0,2,2].map((color,i)=>({color,bonus:i===1?bonus:null,displayDistance:i*24}));s.ball=0;E.step(s,{aim:1,attack:true});while(s.zumaShot)E.step(s,{});assert.ok(s.bonusNotice>0);if(bonus==='bomb')assert.ok(s.picked>=5);if(bonus==='slow')assert.ok(s.slowTicks>0);if(bonus==='back')assert.ok(s.retreatTicks>0);}});

test('reviving Emil restarts the failed round without cascading life losses or resetting completed opponent',()=>{for(const wave of [1,3]){const s=E.create(3,{bossOnly:wave===3});s.score=450;s.picked=15;s.travel=E.zumaPath(wave).length-(s.chain.length-1)*24+1;E.step(s,{});assert.ok(s.lost);const hits=s.hits;E.revive(s);assert.equal(s.wave,wave);assert.equal(s.score,450);assert.equal(s.picked,15);assert.equal(s.travel,0);assert.equal(s.zumaShot,null);assert.equal(s.boss.name,wave===3?'Павел Тертычный':'Робошапка');for(let i=0;i<300;i++)E.step(s,{});assert.equal(s.lost,false);assert.equal(s.hits,hits);assert.ok(s.health>0);}});
