const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-race-engine'),Campaign=require('../app-last-buy-in-campaign-engine'),C=require('../app-last-buy-in-chapters');
function ready(){const s=E.create();s.countdown=0;s.speed=6;return s;}
test('campaign 8 is Pryanik comic and 9 is stadium karting',()=>{assert.equal(C[8].mode,'comic');assert.equal(C[8].hero,'pryanik');assert.equal(C[9].mode,'race');assert.match(C[9].mapLocation,/Стадион/);assert.equal(Campaign.create(8).mode,'comic');assert.equal(Campaign.create(9).mode,'race');});
test('grid countdown freezes every kart',()=>{const s=E.create();for(let i=0;i<179;i++)E.step(s,{right:true});assert.equal(s.distance,0);assert.equal(s.rivals[0].distance,55);E.step(s,{});E.step(s,{});assert.ok(s.distance>0);});
test('timed drift yields up to three turbo boosts, early presses do not',()=>{const s=ready();E.step(s,{jump:true,right:true});E.step(s,{jump:true,special:true});assert.equal(s.boosts,0);s.previous={};E.step(s,{jump:true,left:true});for(let n=0;n<3;n++){s.drift=1;s.driftMeter=65;s.previous={jump:true};E.step(s,{jump:true,special:true});assert.equal(s.boostChain,n+1);}assert.equal(s.boosts,3);assert.ok(s.boost>0);assert.equal(s.drift,0);});
test('grass slows kart and shield absorbs a trap without spin',()=>{const s=ready();s.lateral=1.1;s.boost=80;for(let i=0;i<30;i++)E.step(s,{});assert.ok(s.speed<6);s.lateral=0;s.shield=100;s.traps=[{distance:s.distance+5,lateral:0,enemy:true}];E.step(s,{});assert.equal(s.shield,0);assert.equal(s.spin,0);assert.equal(s.hits,0);});
test('item crate resolves once and rocket targets kart ahead',()=>{const s=ready();s.distance=595;E.step(s,{});assert.ok(s.itemRoll);for(let i=0;i<36;i++)E.step(s,{});assert.ok(s.item);s.item='rocket';s.rivals[0].distance=s.distance+100;E.step(s,{attack:true});assert.equal(s.item,null);for(let i=0;i<30;i++)E.step(s,{});assert.ok(s.rivals[0].stun>0);assert.ok(s.used.has('0:600'));});
test('ramp gives airtime and landing boost; turbo enables inner-sector shortcut',()=>{const s=ready();s.distance=3858;E.step(s,{});assert.ok(s.air>0);for(let i=0;i<48;i++)E.step(s,{});assert.ok(s.boost>0);s.distance=4550;s.lateral=-.8;s.boost=60;E.step(s,{});assert.equal(s.shortcuts,1);assert.ok(s.speed>=8);});
test('full three-lap race is winnable using timed drifts and steering',()=>{const s=E.create();while(!s.won&&!s.lost&&s.tick<7000){const curve=E.road(s.distance).curve,target=curve*.08,steer=s.lateral>target+.03?-1:s.lateral<target-.03?1:curve>0?1:curve<0?-1:0;E.step(s,{left:steer<0,right:steer>0,jump:!!steer,special:s.driftMeter>=65&&!s.previous.special,attack:!!s.item&&!s.previous.attack});}assert.ok(s.won,JSON.stringify({distance:s.distance,position:s.position,hits:s.hits,tick:s.tick}));assert.equal(s.lapTimes.length,3);assert.ok(s.boosts>3);});
test('finish in last place ends race and retry resets grid, no fake distance rewind',()=>{const s=ready();s.distance=E.LAP*3-2;s.rivals.forEach(r=>r.distance=E.LAP*3+100);E.step(s,{});assert.equal(s.finishPosition,4);assert.equal(s.lost,true);const d=s.distance;E.step(s,{});assert.equal(s.distance,d);E.revive(s);assert.equal(s.distance,0);assert.equal(s.countdown,180);});
test('save migration moves comic medal, discards replaced Zuma and retains remaining lives',()=>{const fs=require('fs'),vm=require('vm'),source=fs.readFileSync(require.resolve('../app-last-buy-in-story.js'),'utf8'),start=source.indexOf("try{if(!localStorage.getItem('poker-last-buy-in:stadium-order-v1'))"),end=source.indexOf('let medals={};',start),data=new Map([['poker-last-buy-in:v3',JSON.stringify({7:{score:100},8:{score:200},9:{score:300}})],['poker-last-buy-in:run-v3',JSON.stringify({chapter:9,lives:1,active:true})]]),localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};vm.runInNewContext(source.slice(start,end),{localStorage});const saved=JSON.parse(data.get('poker-last-buy-in:v3'));assert.equal(saved[8].score,300);assert.equal(saved[9],undefined);assert.equal(saved[7].score,100);assert.deepEqual(JSON.parse(data.get('poker-last-buy-in:run-v3')),{chapter:8,lives:1,active:true});vm.runInNewContext(source.slice(start,end),{localStorage});assert.equal(JSON.parse(data.get('poker-last-buy-in:v3'))[8].score,300);});
