const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-comic-engine');
test('comic route and boss can be cleared through movement and combat',()=>{const s=E.create();let lives=0;while(!s.won&&s.tick<12000){const enemy=s.enemies.find(e=>e.hp),target=s.crate.hp?140:enemy?enemy.x:360;const a={attack:true,right:target>s.x+20,left:target<s.x-20,jump:s.tick%85===0,dodge:s.enemies.some(e=>e.windup===10)};if(s.panel===1&&!s.switchOff){a.left=s.x>120;a.right=s.x<100;a.special=Math.abs(s.x-120)<42&&s.tick%2===0;}else a.special=!!enemy&&s.paper>0&&s.tick%120===0;E.step(s,a);if(s.lost){lives++;E.revive(s);}}assert.ok(s.won);assert.equal(s.panel,5);assert.ok(lives<3);});
test('revival preserves enemies, broken crate, disabled current and cleared pages',()=>{const s=E.create();s.crate.hp=0;s.enemies[0].hp=0;s.score=300;s.panel=1;s.switchOff=true;s.lost=true;E.revive(s);assert.equal(s.crate.hp,0);assert.equal(s.enemies[0].hp,0);assert.equal(s.panel,1);assert.equal(s.switchOff,true);assert.equal(s.score,300);assert.equal(s.health,3);});
test('a frontal shield blocks punches but not aerial attacks',()=>{const s=E.create();s.crate.hp=0;s.x=150;s.enemies=[{x:185,y:420,hp:4,max:4,shield:true,face:-1,cooldown:100,stun:0,windup:0}];for(let i=0;i<6;i++)E.step(s,{attack:true});assert.equal(s.enemies[0].hp,4);s.attackCooldown=0;s.previous={};E.step(s,{jump:true,attack:true});for(let i=0;i<5;i++)E.step(s,{attack:true});assert.equal(s.enemies[0].hp,2);});
test('dodge provides protection and has a cooldown',()=>{const s=E.create();E.step(s,{dodge:true});assert.ok(s.inv>0);assert.ok(s.dodgeCooldown>0);const cooldown=s.dodgeCooldown;E.step(s,{});E.step(s,{dodge:true});assert.ok(s.dodgeCooldown<cooldown);});

test('cleared print shop offers two routes which join at the trophy archive',()=>{for(const [action,next]of [['jump',2],['dodge',3]]){const s=E.create();s.panel=1;s.enemies=[];s.crate.hp=0;s.switchOff=true;s.x=350;E.step(s,{});assert.ok(s.routeChoice);E.step(s,{[action]:true});assert.equal(s.nextPanel,next);for(let i=0;i<70;i++)E.step(s,{});assert.equal(s.panel,next);s.enemies=[];s.crate.hp=0;s.switchOff=true;s.puzzleSolved=true;s.x=350;s.ground=true;s.y=420;E.step(s,{});assert.equal(s.nextPanel,4);}});
test('three inventory items act differently and revival preserves spent items',()=>{const s=E.create();s.selected=2;s.health=1;E.step(s,{special:true});assert.equal(s.health,2);assert.equal(s.tea,0);s.previous={};s.selected=0;E.step(s,{special:true});assert.equal(s.shots[0].kind,'paper');assert.equal(s.paper,1);s.previous={};s.selected=1;E.step(s,{special:true});assert.ok(s.shots.some(p=>p.kind==='bomb'));assert.equal(s.bombs,0);s.lost=true;E.revive(s);assert.equal(s.bombs,0);assert.equal(s.tea,0);assert.equal(s.paper,1);});
test('helper disables a distant trap without consuming inventory',()=>{const s=E.create();s.panel=1;s.switchOff=false;s.enemies=[];s.crate.hp=0;E.step(s,{partner:true});for(let i=0;i<40;i++)E.step(s,{});assert.equal(s.switchOff,true);assert.equal(s.helper.done,true);assert.equal(s.paper,2);});
test('guard blocks front, low attack bypasses guard and enemies telegraph tickets',()=>{const s=E.create();s.crate.hp=0;s.x=150;s.enemies=[{kind:'guard',x:185,y:420,hp:4,max:4,shield:true,face:-1,cooldown:100,stun:0,windup:0}];for(let i=0;i<6;i++)E.step(s,{attack:true});assert.equal(s.enemies[0].hp,4);s.attackCooldown=0;for(let i=0;i<6;i++)E.step(s,{down:true,attack:true});assert.equal(s.enemies[0].hp,3);s.hitStop=0;s.move=null;s.enemies=[{kind:'courier',x:240,y:420,hp:3,cooldown:0,stun:0,windup:0,attackCount:0}];E.step(s,{});assert.ok(s.enemies[0].windup>0);assert.equal(s.enemyShots.length,0);for(let i=0;i<32;i++)E.step(s,{});assert.ok(s.enemyShots.length>0);});
test('explosive barrel warns before blast and can damage enemies',()=>{const s=E.create();s.crate.hp=0;s.x=150;s.barrel={x:180,hp:1,fuse:0,spent:false};s.enemies=[{kind:'guard',x:210,y:420,hp:4,max:4,cooldown:200,stun:100,drawIn:0}];for(let i=0;i<6;i++)E.step(s,{attack:true});assert.ok(s.barrel.fuse>0);assert.equal(s.barrel.spent,false);s.x=40;for(let i=0;i<55;i++)E.step(s,{});assert.equal(s.barrel.spent,true);assert.equal(s.enemies[0].hp,0);assert.equal(s.health,3);});
test('crouching avoids high tickets, slow movement remains possible and jump clears crouch',()=>{for(const duck of [true,false]){const s=E.create();s.enemies=[];s.crate.hp=0;s.x=100;s.enemyShots=[{x:110,y:365,dx:-1,life:30}];E.step(s,{down:duck});assert.equal(s.crouch,duck);assert.equal(s.health,duck?3:2);}const s=E.create();s.enemies=[];s.crate.hp=0;const x=s.x;E.step(s,{down:true,right:true});assert.ok(Math.abs(s.x-x-1.2)<1e-9);assert.ok(s.crouch);E.step(s,{down:true,jump:true});assert.equal(s.ground,false);assert.equal(s.crouch,false);});

test('uppercut launches enemies and held attack throws a nearby opponent',()=>{for(const action of [{up:true,attack:true},{attack:true}]){const s=E.create();s.crate.hp=0;s.x=150;s.enemies=[{kind:'guard',x:185,y:420,hp:9,max:9,shield:true,face:-1,cooldown:200,stun:0}];for(let i=0;i<(action.up?6:45);i++)E.step(s,action);assert.ok(s.enemies[0].hp<9);assert.ok(s.enemies[0].airborne||s.enemies[0].hp<=6);}});
test('chain catch, cargo release and pressure plate have gameplay effects',()=>{const s=E.create();s.enemies=[];s.crate.hp=0;s.chain={x:100,y:245,length:120};s.x=100;s.y=365;s.ground=false;s.vy=-1;E.step(s,{up:true});assert.ok(s.hanging);s.cargo={x:130,y:230,vy:0,released:false};for(let i=0;i<6;i++)E.step(s,{attack:true});assert.ok(s.cargo.released);E.step(s,{down:true});assert.equal(s.hanging,false);s.pushBox={x:180,y:420,w:30};s.pressurePlate={x:185};s.puzzleSolved=false;E.step(s,{});assert.equal(s.puzzleSolved,true);E.revive(s);assert.equal(s.puzzleSolved,true);});
test('Editor telegraphs then draws a contextual courier',()=>{const s=E.create();s.panel=4;s.enemies=[];s.crate.hp=0;for(let i=0;i<211;i++)E.step(s,{});assert.ok(s.editorEvent.active);assert.equal(E.clear(s),false);for(let i=0;i<70;i++)E.step(s,{});assert.equal(s.enemies[0].kind,'courier');assert.ok(s.enemies[0].drawIn);});

test('gingerbread boomerang returns to the hero and icing heals',()=>{const s=E.create();s.crate.hp=0;s.enemies=[];s.x=100;E.step(s,{select:0,useSelectedItem:true});for(let i=0;i<25;i++)E.step(s,{});assert.ok(s.shots[0].returning);for(let i=0;i<30;i++)E.step(s,{});assert.equal(s.shots.length,0);s.health=2;E.step(s,{select:2,useSelectedItem:true});assert.equal(s.health,3);assert.ok(s.effects.some(e=>e.text==='ГЛАЗУРЬ +1'));});
test('run cycle follows actual travel and stops against crate or in air',()=>{const s=E.create();s.enemies=[];E.step(s,{right:true});assert.equal(s.moving,true);assert.ok(s.walkDistance>0);s.x=140;const before=s.walkDistance;for(let i=0;i<10;i++)E.step(s,{right:true});assert.equal(s.moving,false);assert.equal(s.walkDistance,before);E.step(s,{jump:true,right:true});assert.equal(s.moving,false);assert.equal(s.ground,false);});
