const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-comic-engine');
test('comic route and boss can be cleared through movement and combat',()=>{const s=E.create();let lives=0;while(!s.won&&s.tick<12000){const enemy=s.enemies.find(e=>e.hp),target=s.crate.hp?140:enemy?enemy.x:360;const a={attack:true,right:target>s.x+20,left:target<s.x-20,jump:s.tick%85===0,dodge:s.enemies.some(e=>e.windup===10)};if(s.panel===1&&!s.switchOff){a.left=s.x>120;a.right=s.x<100;a.special=Math.abs(s.x-120)<42&&s.tick%2===0;}else a.special=!!enemy&&s.paper>0&&s.tick%120===0;E.step(s,a);if(s.lost){lives++;E.revive(s);}}assert.ok(s.won);assert.equal(s.panel,5);assert.ok(lives<3);});
test('revival preserves enemies, broken crate, disabled current and cleared pages',()=>{const s=E.create();s.crate.hp=0;s.enemies[0].hp=0;s.score=300;s.panel=1;s.switchOff=true;s.lost=true;E.revive(s);assert.equal(s.crate.hp,0);assert.equal(s.enemies[0].hp,0);assert.equal(s.panel,1);assert.equal(s.switchOff,true);assert.equal(s.score,300);assert.equal(s.health,3);});
test('a frontal shield blocks punches but not aerial attacks',()=>{const s=E.create();s.crate.hp=0;s.x=150;s.enemies=[{x:185,y:420,hp:4,max:4,shield:true,face:-1,cooldown:100,stun:0,windup:0}];E.step(s,{attack:true});assert.equal(s.enemies[0].hp,4);s.attackCooldown=0;s.previous={};E.step(s,{jump:true,attack:true});assert.equal(s.enemies[0].hp,2);});
test('dodge provides protection and has a cooldown',()=>{const s=E.create();E.step(s,{dodge:true});assert.ok(s.inv>0);assert.ok(s.dodgeCooldown>0);const cooldown=s.dodgeCooldown;E.step(s,{});E.step(s,{dodge:true});assert.ok(s.dodgeCooldown<cooldown);});

test('cleared print shop offers two routes which join at the trophy archive',()=>{for(const [action,next]of [['jump',2],['dodge',3]]){const s=E.create();s.panel=1;s.enemies=[];s.crate.hp=0;s.switchOff=true;s.x=350;E.step(s,{});assert.ok(s.routeChoice);E.step(s,{[action]:true});assert.equal(s.nextPanel,next);for(let i=0;i<55;i++)E.step(s,{});assert.equal(s.panel,next);s.enemies=[];s.crate.hp=0;s.switchOff=true;s.x=350;s.ground=true;s.y=420;E.step(s,{});assert.equal(s.nextPanel,4);}});
test('three inventory items act differently and revival preserves spent items',()=>{const s=E.create();s.selected=2;s.health=1;E.step(s,{special:true});assert.equal(s.health,2);assert.equal(s.tea,0);s.previous={};s.selected=0;E.step(s,{special:true});assert.equal(s.shots[0].kind,'paper');assert.equal(s.paper,1);s.previous={};s.selected=1;E.step(s,{special:true});assert.ok(s.shots.some(p=>p.kind==='bomb'));assert.equal(s.bombs,0);s.lost=true;E.revive(s);assert.equal(s.bombs,0);assert.equal(s.tea,0);assert.equal(s.paper,1);});
test('helper disables a distant trap without consuming inventory',()=>{const s=E.create();s.panel=1;s.switchOff=false;s.enemies=[];s.crate.hp=0;E.step(s,{partner:true});for(let i=0;i<40;i++)E.step(s,{});assert.equal(s.switchOff,true);assert.equal(s.helper.done,true);assert.equal(s.paper,2);});
test('guard blocks front, low attack bypasses guard and enemies telegraph tickets',()=>{const s=E.create();s.crate.hp=0;s.x=150;s.enemies=[{kind:'guard',x:185,y:420,hp:4,max:4,shield:true,face:-1,cooldown:100,stun:0,windup:0}];E.step(s,{attack:true});assert.equal(s.enemies[0].hp,4);s.attackCooldown=0;E.step(s,{down:true,attack:true});assert.equal(s.enemies[0].hp,3);s.enemies=[{kind:'courier',x:240,y:420,hp:3,cooldown:0,stun:0,windup:0,attackCount:0}];E.step(s,{});assert.ok(s.enemies[0].windup>0);assert.equal(s.enemyShots.length,0);for(let i=0;i<32;i++)E.step(s,{});assert.ok(s.enemyShots.length>0);});
test('explosive barrel warns before blast and can damage enemies',()=>{const s=E.create();s.crate.hp=0;s.x=150;s.barrel={x:180,hp:1,fuse:0,spent:false};s.enemies=[{kind:'guard',x:210,y:420,hp:4,max:4,cooldown:200,stun:100,drawIn:0}];E.step(s,{attack:true});assert.ok(s.barrel.fuse>0);assert.equal(s.barrel.spent,false);s.x=40;for(let i=0;i<45;i++)E.step(s,{});assert.equal(s.barrel.spent,true);assert.equal(s.enemies[0].hp,0);assert.equal(s.health,3);});
