const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-campaign-engine'),P=require('../app-last-buy-in-poker-engine');
function ready(s){while(s.dealTicks||s.resultTicks)E.step(s,{});}
function choose(s,bet){ready(s);E.step(s,{bet});}
test('each river scenario uses nine distinct physical cards',()=>{for(const h of P.hands)assert.equal(new Set([...h.hole,...h.board,...h.villain]).size,9);});
test('chips are conserved, folds concede the ante and opponent cards only reveal after a choice',()=>{const s=E.create(4,{seed:42});ready(s);assert.equal(s.revealed,false);const total=s.heroStack+s.rivalStack;const hero=s.heroStack;choose(s,'fold');assert.equal(s.heroStack,hero-1);assert.equal(s.heroStack+s.rivalStack,total);assert.equal(s.revealed,true);assert.ok(s.feedback);});
test('a winning hand still wins chips when called instead of the optimal raise',()=>{const s=E.create(4,{seed:42});while(s.hand.best!=='raise')choose(s,s.hand.best);ready(s);const before=s.heroStack;choose(s,'call');assert.ok(s.heroStack>before);assert.match(s.feedback,/Банк выигран/);});
test('Roboshapka leads to Pavel, and the final requires winning his stack',()=>{const s=E.create(4,{seed:17});let robot=false,pavel=false;while(!s.won&&!s.lost&&s.tick<12000){robot||=s.opponent===0;pavel||=s.opponent===1;E.step(s,{bet:s.hand.best});}assert.equal(s.won,true);assert.equal(s.rivalStack,0);assert.ok(robot&&pavel);assert.ok(s.handsPlayed>=8);});
test('both opponents have separate admin tests and revival preserves the current hand and rival stack',()=>{for(const preBoss of [false,true]){const s=E.create(4,{bossOnly:true,preBoss,seed:8});assert.equal(s.opponent,preBoss?0:1);const hand=s.hand,rival=s.rivalStack;s.heroStack=0;s.health=0;s.lost=true;E.revive(s);assert.equal(s.hand,hand);assert.equal(s.rivalStack,rival);assert.equal(s.heroStack,12);while(!s.won&&!s.lost&&s.tick<12000)E.step(s,{bet:s.hand.best});assert.equal(s.won,true);assert.equal(s.opponent,preBoss?0:1);}});
test('an unanswered hand times out once, costs chips and health, then allows the next decision',()=>{const s=E.create(4,{seed:7});ready(s);s.decisionTicks=1;E.step(s,{});assert.equal(s.health,4);assert.equal(s.heroStack,30);assert.match(s.feedback,/Время вышло/);const health=s.health;for(let i=0;i<100;i++)E.step(s,{});assert.equal(s.health,health);assert.equal(s.handsPlayed,1);});
