const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-campaign-engine'),C=require('../app-last-buy-in-chapters');
test('twelve ordered chapters and five boss encounters, all allies remain allies',()=>{assert.equal(C.length,12);assert.equal(C.filter(c=>c.boss).length,5);assert.equal(C[11].hero,'valera');for(const c of C)assert.ok(c.before&&c.after&&c.goal);assert.deepEqual(C.map(c=>c.mode),['chase','fight','platform','speed','swim','snake','carpet','bomb','zuma','race','portal','final']);});
test('Bomb explosions stop at solid walls and chain into adjacent bombs',()=>{const s=E.create(7);s.bombs=[{x:1,y:1,fuse:1},{x:3,y:1,fuse:99}];E.step(s,{});assert.equal(s.bombs.length,0);assert.ok(s.flames.some(f=>f.x===4&&f.y===1));assert.ok(!s.flames.some(f=>f.x===2&&f.y===2));assert.ok(s.health<5);});
test('Zuma inserts a colour and removes a real matching run; all three batches are completable',()=>{const s=E.create(8);let limit=0;while(!s.won&&limit++<5000){const at=s.chain.findIndex(c=>c.color===s.ball),aim=at<0?0:at;if(at<0){E.step(s,{special:true});E.step(s,{});continue;}E.step(s,{});E.step(s,{aim,attack:true});for(let i=0;i<16;i++)E.step(s,{});}assert.equal(s.won,true);assert.equal(s.wave,3);assert.ok(s.score>1000);});
test('Portals require moving and depositing a cube on each button',()=>{const s=E.create(10);for(let n=0;n<3;n++){s.x=s.panel.x-45;s.y=350;for(let hit=0;hit<3;hit++){s.x=s.panel.x-45;s.y=200;s.vy=0;E.step(s,{attack:true});for(let t=0;t<24;t++)E.step(s,{});}assert.equal(s.panel.hp,0);s.x=s.cube.x;s.y=s.cube.y+20;s.vy=0;E.step(s,{attack:true});assert.equal(s.carry,true);E.step(s,{});s.portalCooldown=0;s.x=s.portals[0].x;s.y=s.portals[0].y;E.step(s,{});assert.equal(s.crossedPortal,true);s.x=s.pad.x-25;s.y=s.pad.y+20;s.vy=0;E.step(s,{attack:true});E.step(s,{});assert.equal(s.puzzles,n+1);}assert.equal(s.won,true);});
test('Snake supports carry the rider; locks do not auto-open and boss must be attacked after warning',()=>{const s=E.create(5);const p=s.platforms[2];s.x=p.x+20;s.y=p.y;s.ground=true;const x=s.x;E.step(s,{});assert.notEqual(s.x,x);assert.equal(s.picked,0);for(const l of s.locks){s.x=l.x;E.step(s,{special:true});}assert.equal(s.picked,3);s.x=s.boss.x-40;s.y=330;E.step(s,{special:true});assert.equal(s.phase,'boss');assert.equal(s.boss.hp,6);});
test('Deaths preserve route progress, collected keys and puzzle state',()=>{for(const chapter of [2,3,4,5,6,7,8,9,10]){const s=E.create(chapter);s.score=333;s.picked=2;s.health=0;s.lost=true;const x=s.x;E.revive(s);assert.equal(s.lost,false);assert.equal(s.health,5);assert.equal(s.x,x);assert.equal(s.score,333);assert.equal(s.picked,2);}});
test('Weapon race requires a first-place finish rather than elapsed time',()=>{const s=E.create(9);s.distance=5399;s.speed=3.8;s.rivals.forEach(r=>r.distance=6000);E.step(s,{up:true});assert.equal(s.won,false);s.distance=5399;s.rivals.forEach(r=>r.distance=5000);E.step(s,{up:true});assert.equal(s.won,true);});
test('Swim requires all keys and exit; surface pockets replenish air',()=>{const s=E.create(4);s.x=150;s.y=130;s.air=100;E.step(s,{});assert.ok(s.air>100);s.x=s.world-50;E.step(s,{});assert.equal(s.won,false);for(const t of s.tokens){s.x=t.x;s.y=t.y;E.step(s,{});}s.x=s.world-50;E.step(s,{});assert.equal(s.won,true);});
test('Speed loop carries the rider through a full circular path, then returns control',()=>{const s=E.create(3);s.x=1160;s.y=430;s.vx=7;E.step(s,{right:true});assert.ok(s.loop);let min=540,max=0;for(let i=0;i<150&&s.loop;i++){E.step(s,{});min=Math.min(min,s.y);max=Math.max(max,s.y);}assert.equal(s.loop,null);assert.ok(min<300&&max>440);assert.ok(s.vx>4);});
test('all nine new chapters can be completed through normal controls, sharing at most three campaign lives',()=>{const {controller}=require('./helpers/last-buy-in-campaign-player.cjs');let spent=0;for(const chapter of [2,3,4,5,6,7,8,9,10]){const s=E.create(chapter);while(!s.won&&s.tick<20000){E.step(s,controller(s));assert.ok(Number.isFinite(s.x)&&Number.isFinite(s.y));if(s.lost){spent++;assert.ok(spent<3,'campaign lives exhausted in chapter '+chapter);E.revive(s);}}assert.equal(s.won,true,'chapter '+chapter+' is not completable');const tick=s.tick;E.step(s,{right:true,attack:true});assert.equal(s.tick,tick);}});
test('Platform obstacles have solid sides, walkable tops and a one-use underside reward',()=>{
 const setup=()=>{const s=E.create(2);s.enemies=[];s.mushrooms=[];s.traps=[];s.pipes=[];s.platforms=[];s.blocks=[{x:100,y:300,w:40,h:30,kind:'question',used:false}];return s;};
 let s=setup();s.x=87;s.y=340;E.step(s,{right:true});assert.equal(s.x,88);
 s=setup();s.x=120;s.y=298;s.vy=4;E.step(s,{});assert.equal(s.y,300);assert.equal(s.ground,true);
 s=setup();s.x=120;s.y=380;s.vy=-10;E.step(s,{});assert.equal(s.y,375);assert.equal(s.blocks[0].used,true);assert.equal(s.picked,1);
 s.y=380;s.vy=-10;E.step(s,{});assert.equal(s.picked,1);
 s=setup();s.blocks[0].kind='brick';s.big=100;s.x=120;s.y=380;s.vy=-10;E.step(s,{});assert.equal(s.blocks[0].broken,true);
});
test('Pipe guard cycles and remains inside while the player stands nearby',()=>{
 const s=E.create(2),p=s.pipes.find(p=>p.plant);s.mushrooms=[];s.enemies=[];s.traps=[];s.tick=130-Math.floor(p.x);s.x=p.x-100;s.y=p.y+60;E.step(s,{});assert.ok(p.extension>0);
 s.x=p.x+p.w/2;s.y=p.y;s.vy=0;E.step(s,{});assert.ok(s.health<5);p.extension=0;s.inv=0;s.health=5;E.step(s,{});assert.equal(p.extension,0);assert.equal(s.health,5);
});
