const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-campaign-engine');
test('final is a short Vaar speed route with an actual boss, not an automatic finish',()=>{const s=E.create(11);assert.equal(s.mode,'speed');assert.equal(s.world,5600);assert.equal(s.health,3);s.x=s.world-30;s.y=450;s.ground=true;E.step(s,{});assert.equal(s.won,false);assert.equal(s.phase,'boss');assert.equal(s.boss.hp,6);});
test('chips absorb a hit and scatter; without chips the three-point health takes damage',()=>{const s=E.create(11);s.rings=12;E.damage(s);assert.equal(s.rings,0);assert.equal(s.health,3);assert.equal(s.scatter.length,12);s.inv=0;E.damage(s);assert.equal(s.health,2);});
test('death keeps collected chips, defeated enemies and boss damage',()=>{const s=E.create(11);s.tokens[0].collected=true;s.enemies[0].hp=0;s.boss.hp=4;s.health=0;s.lost=true;E.revive(s);assert.equal(s.health,3);assert.equal(s.tokens[0].collected,true);assert.equal(s.enemies[0].hp,0);assert.equal(s.boss.hp,4);});
test('route and final boss can be beaten with movement and jumps',()=>{const s=E.create(11);let lives=0;while(!s.won&&s.tick<12000){const floor=s.platforms.find(p=>s.x>=p.x&&s.x<p.x+p.w&&Math.abs(s.y-E.speedSurface(p,s.x))<5),gap=floor&&floor.x+floor.w-s.x<90&&floor.x+floor.w<s.world,spike=s.spikes.some(p=>p.x-s.x>0&&p.x-s.x<100);const jump=s.ground&&(gap||spike||s.phase==='boss'&&s.boss.exposed||s.tick%90===0);E.step(s,{right:s.phase!=='boss'||s.x<(s.boss.exposed?s.boss.x:5070),left:s.phase==='boss'&&s.x>(s.boss.exposed?s.boss.x:5070)+30,jump,down:s.ground&&s.phase==='boss'});if(s.lost){lives++;E.revive(s);}}assert.ok(s.won);assert.equal(s.boss.hp,0);assert.ok(lives<3,'too many lost lives: '+lives);});

test('grounded movement follows slopes without hovering or falling through',()=>{const s=E.create(11);s.enemies=[];s.spikes=[];s.loops=[];s.x=500;s.y=E.speedGround(s,s.x);s.ground=true;for(let i=0;i<25;i++){E.step(s,{right:true});assert.ok(s.ground);assert.ok(Math.abs(s.y-E.speedGround(s,s.x))<.01);}assert.ok(s.y<440);});
test('checkpost restores player position while keeping route rewards',()=>{const s=E.create(11);s.x=1530;s.y=E.speedGround(s,s.x);s.ground=true;E.step(s,{});assert.equal(s.checkpoint,1520);s.tokens[0].collected=true;s.lost=true;s.health=0;s.x=4000;E.revive(s);assert.equal(s.x,1520);assert.equal(s.y,E.speedGround(s,1520));assert.ok(s.tokens[0].collected);});
test('spin charge launches in facing direction and upper monitors give one reward',()=>{const s=E.create(11);for(let i=0;i<25;i++)E.step(s,{special:true});assert.ok(s.charge>=45);E.step(s,{});assert.ok(s.vx>10);s.tokens=[];const m=s.monitors[0];s.x=m.x;s.y=m.y-20;s.vy=0;s.ground=false;s.vx=0;const rings=s.rings;E.step(s,{});assert.ok(m.used);assert.equal(s.rings,rings+10);E.step(s,{});assert.equal(s.rings,rings+10);});
test('boss armor closes before volley and opens during recovery',()=>{const s=E.create(11);s.x=s.boss.x;s.y=410;s.ground=false;s.inv=200;s.boss.timer=10;E.step(s,{});assert.equal(s.boss.hp,6);s.x=s.boss.x;s.y=410;s.vy=0;s.boss.timer=110;E.step(s,{});assert.equal(s.boss.hp,5);});
test('mission 10 is Missclick speed route with bridge terminals and no final boss',()=>{const s=E.create(10);assert.equal(s.mode,'speed');assert.equal(s.missSonic,true);assert.equal(s.boss.hp,0);assert.equal(s.checkposts.length,3);for(const post of s.checkposts){s.x=post.x+1;s.y=E.speedGround(s,s.x);s.ground=true;s.vx=0;s.vy=0;E.step(s,{});}assert.equal(s.bridgePower,3);s.x=s.world-50;s.y=E.speedGround(s,s.x);s.ground=true;s.vy=0;E.step(s,{});assert.ok(s.won);});

test('speed run cycle follows actual ground distance, including coasting, and stops at the boundary',()=>{const s=E.create(10);s.tokens=[];s.enemies=[];s.spikes=[];s.loops=[];s.boostPads=[];s.x=100;s.y=E.speedGround(s,s.x);s.ground=true;s.vx=4;E.step(s,{});assert.ok(s.running);assert.ok(Math.abs(s.runDistance-(s.x-100))<.001);s.x=20;s.y=E.speedGround(s,20);s.vx=-4;E.step(s,{left:true});assert.equal(s.running,false);});
