const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-race-engine'),Campaign=require('../app-last-buy-in-campaign-engine'),C=require('../app-last-buy-in-chapters');
function ready(){const s=E.create();s.countdown=0;s.speed=6;return s;}
test('campaign 8 is Pryanik comic and 9 is stadium karting',()=>{assert.equal(C[8].mode,'comic');assert.equal(C[8].hero,'pryanik');assert.equal(C[9].mode,'race');assert.match(C[9].mapLocation,/Стадион/);assert.equal(Campaign.create(8).mode,'comic');assert.equal(Campaign.create(9).mode,'race');});
test('grid countdown freezes every kart',()=>{const s=E.create();for(let i=0;i<179;i++)E.step(s,{right:true});assert.equal(s.distance,0);assert.equal(s.rivals[0].distance,55);E.step(s,{});E.step(s,{});assert.ok(s.distance>0);});
test('timed drift yields up to three turbo boosts, early presses do not',()=>{const s=ready();E.step(s,{jump:true,right:true});E.step(s,{jump:true,special:true});assert.equal(s.boosts,0);s.previous={};E.step(s,{jump:true,left:true});for(let n=0;n<3;n++){s.drift=1;s.driftMeter=65;s.previous={jump:true};E.step(s,{jump:true,special:true});assert.equal(s.boostChain,n+1);}assert.equal(s.boosts,3);assert.ok(s.boost>0);assert.equal(s.drift,0);});
test('grass slows kart and shield absorbs a trap without spin',()=>{const s=ready();s.lateral=1.1;s.boost=80;for(let i=0;i<30;i++)E.step(s,{});assert.ok(s.speed<6);s.lateral=0;s.shield=100;s.traps=[{distance:s.distance+5,lateral:0,enemy:true}];E.step(s,{});assert.equal(s.shield,0);assert.equal(s.spin,0);assert.equal(s.hits,0);});
test('item crate resolves once and rocket targets kart ahead',()=>{const s=ready();s.distance=595;E.step(s,{});assert.ok(s.itemRoll);for(let i=0;i<36;i++)E.step(s,{});assert.ok(s.item);s.item='rocket';s.rivals[0].distance=s.distance+100;E.step(s,{attack:true});assert.equal(s.item,null);for(let i=0;i<30;i++)E.step(s,{});assert.ok(s.rivals[0].stun>0);assert.ok(s.used.has('0:600'));});
test('ramp gives airtime and landing boost; turbo enables inner-sector shortcut',()=>{const s=ready();s.distance=3858;E.step(s,{});assert.ok(s.air>0);for(let i=0;i<48;i++)E.step(s,{});assert.ok(s.boost>0);s.distance=4550;s.lateral=-.8;s.boost=60;E.step(s,{});assert.equal(s.shortcuts,1);assert.ok(s.speed>=8);});
test('full three-lap race is winnable using timed drifts and steering',()=>{const s=E.create();while(!s.won&&!s.lost&&s.tick<7000){const curve=E.road(s.distance).curve,target=curve*.08,steer=s.lateral>target+.03?-1:s.lateral<target-.03?1:curve>0?1:curve<0?-1:0;E.step(s,{left:steer<0,right:steer>0,jump:!!steer,special:s.driftMeter>=65&&!s.previous.special,attack:!!s.item&&!s.previous.attack});}assert.ok(s.won,JSON.stringify({distance:s.distance,position:s.position,hits:s.hits,tick:s.tick}));assert.equal(s.lapTimes.length,3);assert.ok(s.boosts>3);});
test('finish in last place ends race and retry resets grid, no fake distance rewind',()=>{const s=ready();s.distance=E.LAP*3-2;s.rivals.forEach(r=>r.distance=E.LAP*3+100);E.step(s,{});assert.equal(s.finishPosition,4);assert.equal(s.lost,true);const d=s.distance;E.step(s,{});assert.equal(s.distance,d);E.revive(s);assert.equal(s.distance,0);assert.equal(s.countdown,180);});
test('save migration moves comic medal, discards replaced Zuma and retains remaining lives',()=>{const fs=require('fs'),vm=require('vm'),source=fs.readFileSync(require.resolve('../app-last-buy-in-story.js'),'utf8'),start=source.indexOf("try{if(!localStorage.getItem('poker-last-buy-in:stadium-order-v1'))"),end=source.indexOf('let medals={};',start),data=new Map([['poker-last-buy-in:v3',JSON.stringify({7:{score:100},8:{score:200},9:{score:300}})],['poker-last-buy-in:run-v3',JSON.stringify({chapter:9,lives:1,active:true})]]),localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};vm.runInNewContext(source.slice(start,end),{localStorage});const saved=JSON.parse(data.get('poker-last-buy-in:v3'));assert.equal(saved[8].score,300);assert.equal(saved[9],undefined);assert.equal(saved[7].score,100);assert.deepEqual(JSON.parse(data.get('poker-last-buy-in:run-v3')),{chapter:8,lives:1,active:true});vm.runInNewContext(source.slice(start,end),{localStorage});assert.equal(JSON.parse(data.get('poker-last-buy-in:v3'))[8].score,300);});
test('route is longer and last lap leaves stadium for city then bridge',()=>{assert.ok(E.LAP>7200);assert.equal(E.road(E.LAP+6000).city,false);assert.equal(E.road(E.LAP*2+5000).city,true);assert.equal(E.road(E.LAP*2+9000).bridge,true);const objects=E.trackObjects(E.LAP*2+5000);assert.ok(objects.some(o=>o.kind==='oil'));assert.ok(objects.some(o=>o.kind==='barrier'));assert.ok(objects.filter(o=>o.kind==='ramp').length>=2);});
test('ramp requires alignment, held drift grants longer airtime and stronger landing boost',()=>{let durations=[];for(const held of [false,true]){const s=ready();s.distance=3858;E.step(s,{jump:held});durations.push(s.air);assert.ok(s.air>0);for(let n=0;n<75;n++)E.step(s,{});assert.ok(s.perfectLandings);assert.ok(s.boost>0);}assert.ok(durations[1]>durations[0]);const s=ready();s.distance=3858;s.lateral=.75;E.step(s,{});assert.equal(s.air,0);});
test('road hazards warn first, shield absorbs and airborne kart clears barriers',()=>{for(const protection of ['none','shield','air']){const s=ready();s.distance=2700;s.lateral=-.55;E.step(s,{});assert.equal(s.hazardWarning.kind,'barrier');s.distance=2998;s.lateral=-.55;s[protection==='shield'?'shield':'air']=protection==='none'?0:100;E.step(s,{});assert.equal(s.hits,protection==='none'?1:0);}});
test('ten chips enhance items, impacts drop chips, traps intercept incoming rockets',()=>{const s=ready();s.picked=10;s.item='turbo';E.step(s,{attack:true});assert.ok(s.boost>=220);s.previous={};s.item='shield';E.step(s,{attack:true});assert.ok(s.shield>480);s.shield=0;s.inv=0;s.traps=[{distance:s.distance+5,lateral:s.lateral,enemy:true}];E.step(s,{});assert.equal(s.picked,8);const r=ready();r.item='trap';r.enemyShots=[{distance:-35,lateral:0,enemy:true,life:100}];E.step(r,{attack:true});assert.equal(r.enemyShots.length,0);});
test('late countdown turbo rewards launch and won race actually reaches bridge',()=>{const s=E.create();s.countdown=20;E.step(s,{special:true});for(let i=0;i<19;i++)E.step(s,{});assert.ok(s.boost>0);const r=ready();r.distance=E.LAP*3-2;r.rivals.forEach(k=>k.distance=r.distance-100);E.step(r,{});assert.ok(r.won);assert.ok(r.cupSecured);assert.equal(r.routeZone,'bridge');});
test('rocket removes a road barrier and launched shield stuns a racer',()=>{const s=ready();s.distance=2950;s.enemyShots=[{distance:3000,lateral:-.55,enemy:false,life:100}];E.step(s,{});assert.ok(s.used.has('0:3000'));assert.equal(s.enemyShots.length,0);const r=ready();r.shield=300;r.rivals[0].distance=80;r.rivals[0].lateral=0;E.step(r,{attack:true});assert.equal(r.shield,0);for(let i=0;i<30;i++)E.step(r,{});assert.ok(r.rivals[0].stun>0);});

test('analog steering scales the turn and recenters smoothly',()=>{const gentle=ready(),hard=ready();gentle.rivals=[];hard.rivals=[];for(let n=0;n<12;n++){E.step(gentle,{steer:.25});E.step(hard,{steer:1});}assert.ok(hard.lateral>gentle.lateral*2);const before=hard.steering;E.step(hard,{steer:0});assert.ok(hard.steering>0&&hard.steering<before);for(let n=0;n<30;n++)E.step(hard,{steer:0});assert.ok(hard.steering<.001);});
test('holding drift before steering begins a slide when the turn starts',()=>{const s=ready();E.step(s,{jump:true,steer:0});assert.equal(s.drift,0);for(let i=0;i<4;i++)E.step(s,{jump:true,steer:.7});assert.equal(s.drift,1);E.step(s,{steer:.7});assert.equal(s.drift,0);});
test('rocket remains an offensive projectile when nobody is ahead',()=>{const s=ready();s.rivals.forEach(r=>r.distance=s.distance-100);s.item='rocket';E.step(s,{attack:true});assert.ok(s.enemyShots.some(p=>!p.enemy));assert.equal(s.boost,0);assert.equal(s.item,null);});
test('grass does not repeatedly spin the kart and rival contact has a cooldown',()=>{const s=E.create();s.countdown=0;s.rivals=[];s.distance=100;s.lateral=1.24;for(let n=0;n<120;n++)E.step(s,{});assert.equal(s.hits,0);assert.equal(s.spin,0);assert.ok(s.lateral<1.13);const r=E.create();r.countdown=0;r.distance=100;r.speed=6;r.rivals=[{distance:100,lateral:0,speed:6,stun:0,boost:0,itemAt:99}];E.step(r,{});assert.ok(r.bumpCooldown>0);const pushed=r.lateral;E.step(r,{});assert.equal(r.lateral,pushed);});
test('crash records visual cause and lost chips without repeated damage',()=>{const s=E.create();s.countdown=0;s.distance=500;s.speed=6;s.picked=4;s.rivals=[];s.traps=[{distance:506,lateral:0,enemy:true}];E.step(s,{});assert.equal(s.crash.kind,'trap');assert.equal(s.crash.chips,2);assert.equal(s.picked,2);assert.equal(s.hits,1);s.traps=[{distance:s.distance+3,lateral:0,enemy:true}];E.step(s,{});assert.equal(s.hits,1);});
test('steering release settles lateral momentum and counter-steering reverses promptly',()=>{const s=E.create();s.countdown=0;s.rivals=[];s.speed=6;s.distance=100;for(let i=0;i<15;i++)E.step(s,{steer:.7});assert.ok(s.lateralVelocity>0);const before=s.lateral;for(let i=0;i<20;i++)E.step(s,{steer:0});assert.ok(Math.abs(s.lateralVelocity)<.0001);assert.ok(s.lateral-before<.08);for(let i=0;i<12;i++)E.step(s,{steer:.8});for(let i=0;i<8;i++)E.step(s,{steer:-.8});assert.ok(s.lateralVelocity<0);});
test('drift counter-steering remains controllable and braking decelerates faster',()=>{const s=E.create();s.countdown=0;s.rivals=[];s.speed=6;s.distance=100;for(let i=0;i<8;i++)E.step(s,{steer:1,jump:true});assert.equal(s.drift,1);for(let i=0;i<12;i++)E.step(s,{steer:-1,jump:true});assert.ok(s.lateralVelocity<0);E.step(s,{steer:0});assert.equal(s.drift,0);const brake=E.create(),coast=E.create();for(const v of [brake,coast]){v.countdown=0;v.rivals=[];v.speed=9;v.distance=100;}for(let i=0;i<20;i++){E.step(brake,{down:true});E.step(coast,{});}assert.ok(brake.speed<coast.speed-2);});
