const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-gucci-engine');
test('eight wall panels can be painted to finish within one minute',()=>{const s=E.create();for(const w of s.walls){if(w.id===3||w.id===6){s.x=330;s.y=210;for(let n=0;n<120;n++)E.step(s);}s.x=w.x<40?65:w.x>350?320:w.x;s.y=w.y===160?210:w.y;for(let n=0;n<180;n++)E.step(s,{fire:true,aimX:w.x,aimY:w.y});}assert.equal(E.completed(s),8);assert.equal(s.won,true);assert.ok(s.time>0);});
test('furniture blocks movement and intercepts paint before a wall',()=>{const s=E.create();s.x=115;s.y=370;for(let i=0;i<40;i++)E.step(s,{up:true});assert.ok(s.y>=355);s.x=115;s.y=390;for(let i=0;i<120;i++)E.step(s,{fire:true,aimX:115,aimY:160});assert.ok(s.props[0].paint>0);assert.equal(E.completed(s),0);assert.equal(s.paintedFurniture,1);});
test('painted characters give one reaction count even with repeated hits',()=>{const s=E.create();s.x=195;s.y=290;for(let i=0;i<100;i++)E.step(s,{fire:true,aimX:s.npcs[0].x,aimY:s.npcs[0].y});assert.ok(s.npcs[0].paint>1);assert.equal(s.paintedPeople,1);assert.match(s.notice,/Рома/);});
test('timeout takes one campaign life, retry preserves all painting and gives thirty seconds',()=>{const s=E.create();s.walls[0].paint=18;s.props[0].paint=4;s.time=2;E.step(s);E.step(s);assert.equal(s.lost,true);assert.equal(s.hits,1);for(let i=0;i<50;i++)E.step(s);assert.equal(s.hits,1);E.revive(s);assert.equal(s.time,1800);assert.equal(s.walls[0].paint,18);assert.equal(s.props[0].paint,4);assert.equal(s.lost,false);});
test('Gucci has a stable new chapter ID without changing race or Cooler IDs',()=>{const chapters=require('../app-last-buy-in-chapters');assert.equal(chapters[13].hero,'gucci');assert.equal(chapters[9].mode,'race');assert.equal(chapters[12].mode,'flight');});

test('continuous spraying worsens breathing, and collapse only takes one life',()=>{const s=E.create();for(let i=0;i<1200;i++)E.step(s,{fire:true,aimX:195,aimY:145});assert.equal(s.lost,true);assert.equal(s.lossReason,'fumes');assert.equal(s.condition,3);assert.equal(s.hits,1);const painted=s.props.map(p=>p.paint);E.revive(s);assert.equal(s.exposure,0);assert.equal(E.freshAir(s),true);assert.deepEqual(s.props.map(p=>p.paint),painted);});
test('only releasing spray at the fresh-air doorway quickly recovers breathing',()=>{const s=E.create();s.exposure=80;s.x=330;s.y=210;E.step(s,{fire:true});assert.ok(s.exposure>80);for(let i=0;i<90;i++)E.step(s);assert.ok(s.exposure<5);assert.equal(s.condition,0);s.exposure=80;s.x=195;s.y=455;for(let i=0;i<90;i++)E.step(s);assert.ok(s.exposure>75);});
test('severe fumes reduce movement without reversing input; coughing interrupts the gun',()=>{const s=E.create();s.exposure=90;s.x=195;s.y=440;E.step(s,{right:true,fire:true});assert.ok(s.x>195&&s.x<197.6);assert.ok(s.cough>0);assert.equal(s.shots.length,0);});
