const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-last-buy-in-campaign-engine'),C=require('../app-last-buy-in-chapters');
test('three escalating warehouses have a safe start and a reachable hidden exit',()=>{assert.equal(C[5].mode,'bomb');const s=E.create(5),layouts=[];for(let round=1;round<=3;round++){layouts.push(JSON.stringify(s.grid));assert.equal(s.enemies.length,round+2);assert.equal(s.grid[s.exit.y][s.exit.x],2);assert.equal(s.exit.revealed,false);for(const [x,y]of [[1,1],[2,1],[3,1],[1,2],[1,3]])assert.equal(s.grid[y][x],0);const todo=[[1,1]],seen=new Set();while(todo.length){const [x,y]=todo.shift(),key=x+','+y;if(seen.has(key))continue;seen.add(key);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const v=s.grid[y+dy]?.[x+dx];if(v===0||v===2)todo.push([x+dx,y+dy]);}}assert.ok(seen.has(s.exit.x+','+s.exit.y));s.enemies.forEach(e=>e.hp=0);s.grid[s.exit.y][s.exit.x]=0;s.exit.revealed=true;s.x=s.exit.x;s.y=s.exit.y;E.step(s,{});}assert.equal(new Set(layouts).size,3);assert.equal(s.won,true);assert.equal(s.cardParts,3);});
test('one starting bomb, blocked reentry and wall-stopped chain explosions',()=>{const s=E.create(5);assert.equal(s.bombCapacity,1);assert.equal(s.bombRange,1);s.enemies=[];E.step(s,{attack:true});assert.equal(s.bombs[0].fuse,179);E.step(s,{right:true});assert.equal(s.x,2);s.moveCooldown=0;E.step(s,{left:true});assert.equal(s.x,2);s.x=1;s.y=3;E.step(s,{});s.bombs=[{x:1,y:1,fuse:1,range:2},{x:3,y:1,fuse:90,range:2}];E.step(s,{});assert.equal(s.bombs.length,0);assert.ok(s.flames.some(f=>f.x===3&&f.y===1));assert.ok(!s.flames.some(f=>f.x===2&&f.y===2));});
test('powerups increase range and capacity; a hit preserves the current warehouse',()=>{const s=E.create(5);s.enemies=[];s.bombItems=[{x:1,y:1,type:'range'},{x:1,y:1,type:'capacity'}];E.step(s,{});assert.equal(s.bombRange,2);assert.equal(s.bombCapacity,2);s.cardParts=1;s.bombRound=2;s.inv=0;E.damage(s);assert.equal(s.lost,true);E.revive(s);assert.equal(s.cardParts,1);assert.equal(s.bombRound,2);assert.equal(s.x,1);assert.equal(s.enemies.length,0);assert.equal(s.exit.revealed,false);});
test('exit must be revealed, enemies defeated and flame-free before entering',()=>{const s=E.create(5);s.x=s.exit.x;s.y=s.exit.y;s.inv=999;s.enemies.forEach(e=>e.hp=0);E.step(s,{});assert.equal(s.cardParts,0);s.grid[s.exit.y][s.exit.x]=0;s.exit.revealed=true;s.enemies=[{x:1,y:7,hp:1}];E.step(s,{});assert.equal(s.cardParts,0);s.enemies=[];s.flames=[{x:s.exit.x,y:s.exit.y,life:10}];E.step(s,{});assert.equal(s.cardParts,0);s.flames=[];E.step(s,{});assert.equal(s.cardParts,1);});
test('bomb reveals the exit and the warehouse timer costs a life',()=>{const s=E.create(5);s.enemies=[];s.x=1;s.y=1;s.exit={x:7,y:9,revealed:false,open:false};s.grid[9][7]=2;s.grid[9][6]=0;s.bombs=[{x:6,y:9,fuse:1,range:1}];E.step(s,{});assert.equal(s.exit.revealed,true);assert.equal(s.grid[9][7],0);s.bombTime=1;E.step(s,{});assert.equal(s.lost,true);});

test('classic arenas have a regular pillar lattice and concealed bonuses',()=>{const s=E.create(5);for(let round=1;round<=3;round++){assert.equal(s.grid.length,11);assert.equal(s.grid[0].length,13);for(let y=0;y<11;y++)for(let x=0;x<13;x++)if(x===0||y===0||x===12||y===10||x%2===0&&y%2===0)assert.equal(s.grid[y][x],1);for(const item of s.hiddenBombItems)assert.equal(s.grid[item.y][item.x],2);assert.ok(s.enemies.every(e=>e.x+e.y>5));s.enemies.forEach(e=>e.hp=0);s.grid[s.exit.y][s.exit.x]=0;s.exit.revealed=true;s.x=s.exit.x;s.y=s.exit.y;E.step(s,{});}});
test('bomb fuse lasts three seconds and flames form a wall-stopped cross',()=>{const s=E.create(5);s.enemies=[];s.inv=999;s.grid[3][3]=0;s.grid[3][4]=0;s.grid[3][5]=2;s.x=3;s.y=3;s.bombRange=4;E.step(s,{attack:true});for(let i=0;i<178;i++)E.step(s,{});assert.equal(s.flames.length,0);E.step(s,{});assert.ok(s.flames.some(f=>f.x===3&&f.y===3&&f.axis==='center'));assert.ok(s.flames.some(f=>f.x===4&&f.y===3&&f.axis==='horizontal'));assert.ok(s.flames.some(f=>f.x===5&&f.y===3));assert.ok(!s.flames.some(f=>f.x===6&&f.y===3));assert.ok(s.flames.every(f=>f.x===3||f.y===3));});
test('speed, kick, remote and bomb pass have separate effects',()=>{const s=E.create(5);s.enemies=[];s.inv=999;for(const type of ['speed','kick','remote','pass']){s.bombItems=[{x:s.x,y:s.y,type}];E.step(s,{});}assert.equal(s.bombSpeed,2);assert.ok(s.bombKick&&s.bombRemote&&s.bombPass);s.x=1;s.y=1;E.step(s,{attack:true});assert.ok(s.bombs[0].remote);for(let i=0;i<200;i++)E.step(s,{});assert.equal(s.flames.length,0);s.moveCooldown=0;E.step(s,{right:true});assert.equal(s.moveCooldown,6);s.bombKick=false;s.moveCooldown=0;E.step(s,{left:true});assert.equal(s.x,1);E.step(s,{special:true});assert.equal(s.bombs.length,0);assert.ok(s.flames.length>0);});
test('kick sends a bomb down a corridor and stops at masonry',()=>{const s=E.create(5);s.enemies=[];s.inv=999;s.bombKick=true;s.bombs=[{x:2,y:1,fuse:170,range:1}];s.grid[1][3]=0;s.grid[1][4]=0;s.grid[1][5]=1;E.step(s,{right:true});assert.equal(s.x,2);assert.equal(s.bombs[0].x,3);for(let i=0;i<12;i++)E.step(s,{});assert.equal(s.bombs[0].x,4);assert.equal(s.bombs[0].slide,null);});
test('flame protection blocks fire but not touching an enemy',()=>{const s=E.create(5);s.inv=0;s.enemies=[];s.fireGuard=100;s.flames=[{x:s.x,y:s.y,life:20}];E.step(s,{});assert.equal(s.lost,false);s.flames=[];s.enemies=[{x:s.x,y:s.y,hp:1}];E.step(s,{});assert.equal(s.lost,true);});
test('newly uncovered bonus survives reveal blast but a later blast burns it',()=>{const s=E.create(5);s.inv=999;s.enemies=[];s.grid[3][3]=2;s.grid[3][2]=0;s.bombs=[{x:2,y:3,fuse:1,range:1}];E.step(s,{});assert.ok(s.bombItems.some(i=>i.x===3&&i.y===3));s.bombs=[{x:2,y:3,fuse:1,range:1}];E.step(s,{});assert.ok(!s.bombItems.some(i=>i.x===3&&i.y===3));});
test('every planted trash hand has different suits and rank pairs cycle without repeats',()=>{const s=E.create(5);s.enemies=[];s.inv=10000;const pairs=[];for(let n=0;n<45;n++){s.bombs=[];E.step(s,{});E.step(s,{attack:true});const hand=s.bombs[0].hand;assert.notEqual(hand[0].suit,hand[1].suit);assert.notEqual(hand[0].rank,hand[1].rank);const pair=hand.map(c=>c.rank).join('');assert.notEqual(pair,pairs.at(-1));pairs.push(pair);}assert.equal(new Set(pairs.slice(0,21)).size,21);assert.ok(pairs.includes('73')&&pairs.includes('K4')&&pairs.includes('Q2'));});
