'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),P=require('../lib/lounge-presence');
function table(overrides={}){return {deskId:'1',leagueId:'184691',unionId:'1',groupId:'1',playerCount:1,playType:'NLH',blindAnnotation:'20/40р',pos:{pos1:'9007199254740993',pos2:0},...overrides};}
test('seating uses exact linked ID and exposes game, limit and multiple tables',()=>{const p=P.identify([table(),table({deskId:'2',playType:'PLO5',blindAnnotation:'50/100 ₽'})],'9007199254740993');assert.equal(p.status,'playing');assert.deepEqual(p.tables.map(t=>t.label),['NLH 20/40','PLO5 50/100']);assert.equal(P.identify([table()],'9007199254740992').status,'away');assert.equal(P.identify([table()],'0').status,'unlinked');});
test('missing seating means unknown; known absence or empty table means away',()=>{assert.equal(P.identify([table({pos:null})],'22').status,'unknown');assert.equal(P.identify([table({pos:{pos1:22}}),table({pos:null})],'22').status,'playing');assert.equal(P.identify([table({playerCount:0,pos:{pos1:22}})],'22').status,'away');assert.equal(P.identify([],'22').status,'away');assert.equal(P.label(table({blindAnnotation:'unknown',playType:'PLO'})),'PLO');});
test('personal character has a safe known fallback and canonical nickname mapping',()=>{assert.equal(P.character('Waaaarr',{},'ID2'),'waaar');assert.equal(P.character('Бабник',{},'ID2'),'babnik');assert.equal(P.character('Other',{characterId:'../../etc/passwd'},'ID2'),'pokermanki');assert.equal(P.character('Other',{characterId:'cooler'},'ID2'),'cooler');});
function setup(){let time=100000,fail=false,calls=0;const store=new Map(),tables=[table()];return {store,tables,setTime:v=>time=v,setFail:v=>fail=v,calls:()=>calls,service:P.create({now:()=>time,getTables:async()=>{calls++;if(fail)throw Error('vendor offline');return tables;},redis:async commands=>commands.map(c=>c[0]==='SMEMBERS'?['ID2','ID3','not-an-account']:c[0]==='HGET'?(c[1].endsWith('user_ids')?(c[2]==='ID2'?'9007199254740993':null):JSON.stringify({nickname:c[2]==='ID2'?'Waaar':'Other'})):c[0]==='GET'?store.get(c[1])||null:c[0]==='SET'?(store.set(c[1],c[2]),'OK'):null)})};}
test('server only returns friends, never exposes binding IDs and caches for 15 seconds',async()=>{const f=setup();const [a,b]=await Promise.all([f.service.read('ID1'),f.service.read('ID1')]);assert.equal(f.calls(),1);assert.equal(a.friends.length,2);assert.equal(a.friends[0].status,'playing');assert.equal(a.friends[0].characterId,'waaar');assert.equal(a.friends[1].status,'unlinked');assert.equal(JSON.stringify(a).includes('9007199254740993'),false);assert.deepEqual(a,b);f.setTime(110000);await f.service.read('ID1');assert.equal(f.calls(),1);f.setTime(116000);f.tables[0].pos={pos1:0};f.tables[0].playerCount=0;const next=await f.service.read('ID1');assert.equal(next.friends[0].status,'away');assert.equal(f.calls(),2);});
test('expired snapshot and API failure cannot keep a friend online or mark them offline',async()=>{const f=setup();await f.service.read('ID1');f.setTime(116000);f.setFail(true);const d=await f.service.read('ID1');assert.equal(d.available,false);assert.equal(d.friends[0].status,'unknown');assert.equal(d.friends[1].status,'unlinked');assert.deepEqual(d.friends[0].tables,[]);});

test('character reads are limited to five verified selected friends',async()=>{const reads=[];const service=P.create({getTables:async()=>[],redis:async commands=>commands.map(c=>{reads.push(c);return c[0]==='SMEMBERS'?['ID2','ID3','ID4']:c[0]==='HGET'&&c[1].endsWith('user_ids')?'22':null;})});await service.read('ID1',['ID3','ID999','ID3']);assert.deepEqual(reads.filter(c=>c[0]==='GET'&&c[1].includes('profile_hero')).map(c=>c[1]),['poker_app:profile_hero:ID3']);assert.equal(reads.filter(c=>c[0]==='HGET'&&c[1].endsWith('user_ids')).length,3);assert.equal(P.identify([table({pos:{}})],'22').status,'unknown');assert.equal(P.identify([table({playerCount:2})],'22').status,'unknown');});
