const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../app-monkey-race-engine'),C=require('../app-monkey-race-campaign');
function boss(cycle=0){const s=E.create(270221,5),c=C.create();s.passes=c.goal;s.nextId=1;s.spawnDistance=-1000000;c.phase='boss';c.cycle=cycle;return {s,c};}
function play(s,c){if(s.tick-s.lastInput<7)return 0;let lane=s.lane,duck=false;if(c.attack==='ram'&&c.warning)lane=(c.lane+1)%3;if(c.attack==='shots')duck=c.tick>=60&&c.tick<c.impact+80;if(c.attack==='cops'&&c.tick>=65)lane=(c.lane+2)%3;if(c.attack==='duck')duck=c.tick>=60&&c.tick<=c.impact;if(s.duck!==duck)return duck?5:6;if(s.lane!==lane)return lane<s.lane?1:2;if(c.attack==='jump'&&c.tick===c.impact-20)return 3;return 0;}
test('all five attacks are survivable with real controls and six ram crashes win',()=>{const {s,c}=boss(),attacks=new Set();let crashFrames=0;while(s.alive&&s.tick<12000){attacks.add(c.attack);C.step(c,s,play(s,c));if(c.defeated&&!c.won)crashFrames++;}assert.equal(c.won,true);assert.equal(c.hp,0);assert.equal(attacks.size,5);assert.ok(crashFrames>=69,'final crash is visible before victory');assert.ok(s.tick>3000);});
test('ignoring the marked ram lane loses a life without damaging the captain',()=>{const {s,c}=boss();while(s.alive&&s.tick<500)C.step(c,s,0);assert.equal(s.alive,false);assert.equal(c.hp,6);assert.equal(c.crashed,false);});
test('shots hit a standing player but ducking avoids both bursts',()=>{for(const duck of [false,true]){const {s,c}=boss(1);while(s.alive&&c.cycle===1)C.step(c,s,duck?play(s,c):0);assert.equal(s.alive,duck);assert.equal(c.hp,6);}});
test('troopers cover two lanes and leave an accessible escape lane',()=>{const {s,c}=boss(4);while(s.alive&&c.cycle===4)C.step(c,s,play(s,c));assert.equal(s.alive,true);assert.equal(new Set(c.troopers.map(p=>p.lane)).size,2);assert.equal(c.hp,6);});
test('reviving resets boss hazards while retaining damaged armour',()=>{const {s,c}=boss(1);while(s.alive)C.step(c,s,0);c.hp=5;C.revive(c,s);assert.equal(s.alive,true);assert.equal(c.hp,5);assert.equal(c.projectiles.length,0);assert.equal(c.troopers.length,0);assert.equal(c.inv,180);});

test('story route ends at 90 gates and its bonus life stays within gates 70–90',()=>{for(let i=0;i<100;i++){const c=C.create();assert.equal(c.goal,90);assert.equal(c.maxHp,6);assert.ok(c.heartGate>=70&&c.heartGate<=90);}const {s,c}=boss();c.phase='route';s.passes=89;C.step(c,s,0);assert.equal(c.phase,'route');s.passes=90;C.step(c,s,0);assert.equal(c.phase,'boss');});

test('the third lane is safe when the captain sends troopers down lanes one and two',()=>{const {s,c}=boss(4);s.lane=0;s.y=240;while(c.tick<65)C.step(c,s,0);assert.deepEqual(c.troopers.map(t=>t.lane),[0,1]);while(s.lane<2)C.step(c,s,s.tick-s.lastInput>=7?2:0);while(c.cycle===4&&s.alive)C.step(c,s,0);assert.equal(s.alive,true);assert.equal(s.lane,2);});
test('each visible trooper lane is dangerous on contact, including the third',()=>{for(const lane of [0,1,2]){const {s,c}=boss(4);s.lane=lane;s.y=240+lane*105;while(c.cycle===4&&s.alive)C.step(c,s,0);assert.equal(s.alive,false,'trooper lane '+lane);assert.ok(c.troopers.some(t=>t.lane===lane));}});
