const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../app-monkey-race-engine'),C=require('../app-monkey-race-campaign');
function boss(cycle=0){const s=E.create(270221,5),c=C.create();s.passes=c.goal;s.nextId=1;s.spawnDistance=-1000000;c.phase='boss';c.cycle=cycle;return {s,c};}
function play(s,c){if(s.tick-s.lastInput<7)return 0;let lane=s.lane,duck=false;if(c.attack==='ram'&&c.warning)lane=(c.lane+1)%3;if(c.attack==='shots')duck=c.tick>=60&&c.tick<c.endTick;const danger=c.troopers.filter(t=>!t.hit&&t.x<250&&t.age>t.release);if(danger.some(t=>t.lane===s.lane))lane=[0,1,2].find(n=>!danger.some(t=>t.lane===n))??s.lane;const h=c.hazards.filter(h=>!h.hit).sort((a,b)=>a.impact-b.impact)[0];if(h?.kind==='overhead'&&h.impact-c.tick<45)duck=true;if(s.duck!==duck)return duck?5:6;if(s.lane!==lane)return lane<s.lane?1:2;if(h?.kind==='fulljump'&&h.impact-c.tick<=23&&h.impact-c.tick>=12&&!s.jump)return 3;return 0;}
test('all five attacks are survivable with real controls and six ram crashes win',()=>{const {s,c}=boss(),attacks=new Set();let crashFrames=0;while(s.alive&&s.tick<12000){attacks.add(c.attack);C.step(c,s,play(s,c));if(c.defeated&&!c.won)crashFrames++;}assert.equal(c.won,true);assert.equal(c.hp,0);assert.equal(attacks.size,5);assert.ok(crashFrames>=69,'final crash is visible before victory');assert.ok(s.tick>3000);});
test('ignoring the marked ram lane loses a life without damaging the captain',()=>{const {s,c}=boss();while(s.alive&&s.tick<500)C.step(c,s,0);assert.equal(s.alive,false);assert.equal(c.hp,6);assert.equal(c.crashed,false);});
test('shots hit a standing player but ducking avoids both bursts',()=>{for(const duck of [false,true]){const {s,c}=boss(1);while(s.alive&&c.cycle===1)C.step(c,s,duck?play(s,c):0);assert.equal(s.alive,duck);assert.equal(c.hp,6);}});
test('troopers cover two lanes and leave an accessible escape lane',()=>{const {s,c}=boss(4);while(s.alive&&c.cycle===4)C.step(c,s,play(s,c));assert.equal(s.alive,true);assert.equal(new Set(c.troopers.map(p=>p.lane)).size,2);assert.equal(c.hp,6);});
test('reviving resets boss hazards while retaining damaged armour',()=>{const {s,c}=boss(1);while(s.alive)C.step(c,s,0);c.hp=5;C.revive(c,s);assert.equal(s.alive,true);assert.equal(c.hp,5);assert.equal(c.projectiles.length,0);assert.equal(c.troopers.length,0);assert.equal(c.inv,180);});

test('story route ends at 90 gates and its bonus life stays within gates 70–90',()=>{for(let i=0;i<100;i++){const c=C.create();assert.equal(c.goal,90);assert.equal(c.maxHp,6);assert.ok(c.heartGate>=70&&c.heartGate<=90);}const {s,c}=boss();c.phase='route';s.passes=89;C.step(c,s,0);assert.equal(c.phase,'route');s.passes=90;C.step(c,s,0);assert.equal(c.phase,'approach');});

test('the third lane is safe when the captain sends troopers down lanes one and two',()=>{const {s,c}=boss(4);s.lane=0;s.y=240;while(c.tick<65)C.step(c,s,0);assert.deepEqual(c.troopers.map(t=>t.lane),[0,1]);while(s.lane<2)C.step(c,s,s.tick-s.lastInput>=7?2:0);while(c.cycle===4&&s.alive)C.step(c,s,0);assert.equal(s.alive,true);assert.equal(s.lane,2);});
test('each visible trooper lane is dangerous on contact, including the third',()=>{for(const lane of [0,1,2]){const {s,c}=boss(4);s.lane=lane;s.y=240+lane*105;while(c.cycle===4&&s.alive)C.step(c,s,0);assert.equal(s.alive,false,'trooper lane '+lane);assert.ok(c.troopers.some(t=>t.lane===lane));}});

test('gate closes before dialogue; dialogue pauses the scene and only Next starts the stationary fight',()=>{const s=E.create(1),c=C.create();C.enterBoss(c,s);const distance=s.distance,tick=s.tick;for(let i=0;i<90;i++)C.step(c,s,2);assert.equal(c.phase,'dialogue');assert.equal(c.gateClosed,true);for(let i=0;i<120;i++)C.step(c,s,3);assert.equal(s.tick,tick);assert.equal(s.distance,distance);assert.equal(c.hp,6);for(let i=0;i<C.dialogue.length;i++)C.nextDialogue(c);assert.equal(c.phase,'boss');for(let i=0;i<60;i++)C.step(c,s,0);assert.equal(s.distance,distance);assert.ok(s.tick>tick);});

test('all armour stages have multi-lane volleys with a real safe lane and a faster tempo',()=>{let previous=null;for(let hp=6;hp>=1;hp--){const {s,c}=boss(1);c.hp=hp;let volleys=0;while(c.cycle===1&&s.alive){let action=0;const incoming=c.projectiles.filter(p=>!p.hit).sort((a,b)=>a.x-b.x)[0];if(incoming){const lanes=c.projectiles.filter(p=>p.volley===incoming.volley).map(p=>p.lane),free=[0,1,2].find(l=>!lanes.includes(l));if(s.lane!==free&&s.tick-s.lastInput>=7)action=free<s.lane?1:2;}C.step(c,s,action);volleys=Math.max(volleys,c.volleys);}assert.equal(s.alive,true,'dodging volleys at hp '+hp);assert.ok(volleys>=4);for(let i=0;i<volleys;i++)assert.equal(new Set(c.projectiles.filter(p=>p.volley===i).map(p=>p.lane)).size,2);if(previous){assert.ok(c.volleyGap<previous.gap);assert.ok(c.shotSpeed>previous.speed);assert.ok(c.shotWarning<previous.warning);}previous={gap:c.volleyGap,speed:c.shotSpeed,warning:c.shotWarning};}});
test('multiple jump and duck obstacles remain survivable at every armour stage',()=>{let previousGap=Infinity;for(let hp=6;hp>=1;hp--){for(const cycle of [2,5]){const {s,c}=boss(cycle);c.hp=hp;while(c.cycle===cycle&&s.alive)C.step(c,s,play(s,c));assert.equal(s.alive,true,'series '+cycle+' at hp '+hp);assert.equal(c.hazards.length+c.troopers.length,c.hazardCount);assert.ok(new Set(c.hazardPlan).size>=2);assert.ok(c.hazardPlan.includes('cop'));assert.ok(c.hazards.every(h=>h.hit));if(cycle===2){assert.ok(c.hazardGap<previousGap);previousGap=c.hazardGap;}}}});

test('90th gate leads to 2.5 seconds of clear driving before the boss arrives',()=>{const {s,c}=boss();c.phase='route';s.obstacles=[{kind:'table',x:480,lane:1,id:10,scored:false}];C.step(c,s,0);assert.equal(c.phase,'approach');const distance=s.distance,score=s.score,coins=s.perfect;for(let i=0;i<149;i++){C.step(c,s,i===0?2:0);assert.equal(c.phase,'approach');assert.deepEqual(s.obstacles,[]);assert.equal(c.hp,6);assert.equal(c.tick,0);assert.equal(s.alive,true);}assert.ok(s.distance>distance+800);assert.equal(s.passes,90);assert.equal(s.perfect,coins);assert.equal(s.score,score);C.step(c,s,0);assert.equal(c.phase,'closing');const stopped=s.distance;for(let i=0;i<90;i++)C.step(c,s,0);assert.equal(s.distance,stopped);assert.equal(c.phase,'dialogue');});

test('random mixed series stay survivable and troopers visibly exit before rushing',()=>{for(let run=0;run<60;run++){const {s,c}=boss(run%2?2:5);c.hp=1+run%6;while(s.alive&&c.cycle===(run%2?2:5))C.step(c,s,play(s,c));assert.equal(s.alive,true,'mixed run '+run);assert.ok(c.hazardPlan.includes('cop'));for(let i=1;i<c.hazardPlan.length;i++)assert.notEqual(c.hazardPlan[i],c.hazardPlan[i-1]);}const {s,c}=boss(4);while(c.tick<65)C.step(c,s,0);const cop=c.troopers[0];assert.ok(cop.x>=310&&cop.x<332);for(let i=0;i<40;i++)C.step(c,s,0);assert.equal(cop.x,330);while(cop.age<=cop.release)C.step(c,s,0);assert.ok(cop.x<330);});
