'use strict';const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app-monkey-race-engine'),{fixture}=require('./helpers/cooler-flight-fixture.cjs');
function race(seed,version){const s=E.create(seed,version),taps=[],base=s.version>=3?7:5;while(s.alive){let a=0;const hazard=s.obstacles.find(o=>o.kind!=='coin'&&o.x>s.x-45&&o.x<s.x+160&&(o.lane===s.lane||o.kind==='fulljump'||o.kind==='overhead'));const speed=Math.min(6.2,3.2+(s.stage-1)*.22);if(s.tick-s.lastInput>=7){if(hazard?.kind==='overhead'&&hazard.x<s.x+100&&!s.duck)a=5;else if(s.duck&&(!hazard||hazard.kind!=='overhead'))a=6;else if(hazard?.kind==='fulljump'&&hazard.x<s.x+24+speed*8&&s.jump===0)a=3;else if(hazard&&!['fulljump','overhead'].includes(hazard.kind))a=s.lane===0?2:1;}if(a)taps.push(s.tick*base+a);E.step(s,a);}return {s,taps};}
test('race tracks are deterministic and keep one safe lane',()=>{for(let seed=0;seed<20;seed++){const {s,taps}=race(seed,4);assert.equal(s.tick,3600);assert.equal(s.finished,true);assert.deepEqual(E.replay(seed,taps,s.tick,4),s);assert.ok(s.passes>30);}});
test('jump clears chips while tables require a different lane',()=>{for(const kind of ['chips','table']){const s=E.create(1);s.nextId=10;s.jump=55;s.obstacles=[{x:98,lane:1,kind,scored:false}];E.step(s,0);assert.equal(s.alive,kind==='chips');}});
test('fabricated scores and malformed inputs cannot pass replay',()=>{assert.throws(()=>E.replay(1,[1,6],100));assert.throws(()=>E.replay(1,[0],100));assert.throws(()=>E.replay(1,[],1));});
test('verified solo record and one-minute same-track duel rematch',async()=>{const f=fixture({race:true});const start=(await f.request({action:'start'})).data;const {s,taps}=race(start.seed);f.advance(s.tick*1000/60+1000);let result=await f.request({action:'finish',runId:start.runId,ticks:s.tick,taps,score:9999999});assert.equal(result.status,200);assert.equal(result.data.best,s.score);assert.equal((await f.request({action:'finish',runId:start.runId,ticks:s.tick,taps})).status,409);
const host=(await f.request({action:'create'})).data,guest=(await f.request({action:'join',roomId:host.roomId},'Bob')).data;assert.equal(host.seed,guest.seed);const flight=race(host.seed,4);f.advance(65000);assert.equal((await f.request({action:'finish',runId:host.runId,ticks:flight.s.tick,taps:flight.taps})).status,200);assert.equal((await f.request({action:'finish',runId:guest.runId,ticks:flight.s.tick,taps:flight.taps},'Bob')).status,200);await f.request({action:'rematch',roomId:host.roomId,runId:host.runId});result=await f.request({action:'rematch',roomId:host.roomId,runId:guest.runId},'Bob');assert.equal(result.status,200);assert.equal(result.data.round,2);assert.equal(result.data.roomId,host.roomId);});
test('boost requires three collected chips and each charge is consumed once',()=>{const s=E.create(1);E.step(s,4);assert.equal(s.boosts,0);s.tick=7;s.perfect=3;E.step(s,4);assert.equal(s.boosts,1);assert.equal(s.boostUntil,97);const boosted=s.distance;s.tick=14;E.step(s,4);assert.equal(s.boosts,1);assert.ok(s.distance-boosted>3.2);});
test('full-width barriers cannot be dodged and overhead gates need sustained duck',()=>{for(const lane of [0,1,2]){for(const kind of ['fulljump','overhead']){const s=E.create(1);s.nextId=10;s.lane=lane;s.y=240+lane*105;s.obstacles=[{x:98,lane:0,kind,scored:false}];E.step(s,0);assert.equal(s.alive,false);const safe=E.create(1);safe.nextId=10;safe.lane=lane;safe.y=240+lane*105;safe.obstacles=[{x:98,lane:0,kind,scored:false}];if(kind==='fulljump'){safe.jump=55;}else safe.duck=true;E.step(safe,0);assert.equal(safe.alive,true);}}const held=E.create(1);E.step(held,5);assert.equal(held.duck,true);for(let i=0;i<8;i++)E.step(held,0);assert.equal(held.duck,true);E.step(held,6);assert.equal(held.duck,false);});
