'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),L=require('../lib/player-lounge');
const friends=['ID1','ID2','ID3','ID4','ID5','ID6'].map(accountId=>({accountId}));
test('five lounge places reject outsiders, duplicates and malformed saves',()=>{assert.deepEqual(L.seats(undefined,friends),['ID1','ID2','ID3','ID4','ID5']);assert.deepEqual(L.seats([null,'ID6',null,'ID2',null],friends,true),[null,'ID6',null,'ID2',null]);for(const value of [['ID1','ID1',null,null,null],['ID99',null,null,null,null],['ID1'],null])assert.throws(()=>L.seats(value,friends,true),{status:400});});
test('removing a friend leaves their seat empty and preserves other places',()=>{assert.deepEqual(L.seats(['ID1','IDgone','ID2',null,'ID6'],friends),['ID1',null,'ID2',null,'ID6']);assert.deepEqual(L.seats(['ID1','ID1',null,null,null],friends),['ID1',null,null,null,null]);});
test('lounge image URLs reject executable and traversal-like local sources',()=>{assert.equal(L.avatar('javascript:alert(1)'),null);assert.equal(L.avatar('data:image/svg+xml,<svg/>'),null);assert.equal(L.avatar('./assets/avatar-tiger.jpg'),'./assets/avatar-tiger.jpg');assert.equal(L.avatar('https://example.com/avatar.jpg'),'https://example.com/avatar.jpg');});
test('empty roster requires no external calls and visitors cannot edit seats',async()=>{const progress=await L.read('ID1',[],()=>{throw Error('unexpected redis');});assert.deepEqual(progress,{friends:[],available:true});assert.equal(L.view({},progress,false).editable,false);assert.equal(L.view({},progress,true).editable,true);});
test('roster trusts friendship IDs and confirmed tournament and race data only',async()=>{const fs=require('fs'),vm=require('vm'),path=require('path'),{createRequire}=require('module'),file=path.resolve('lib/player-lounge.js'),base=createRequire(file),module={exports:{}};vm.runInNewContext(fs.readFileSync(file,'utf8'),{module,require:id=>id==='./api-handlers/friends'?{readNewsFriends:async()=>({friends:[{userId:'ID2',pokerPlusNickname:'Waaar',avatarUrl:'javascript:alert(1)',statusLevel:12},{userId:'ID999',pokerPlusNickname:'Other'}]})}:id==='./player-hall-tournament-results.json'?[{nick:'Waaar',place:1,reward:250000,tournament:'Март',date:'2026-03-01'},{nick:'Waaar',place:2,reward:500000,tournament:'Приз',date:'2026-04-01'},{nick:'Other',place:1,reward:999999}]:base(id)});const d=await module.exports.read('ID1',['ID2'],async commands=>{assert.equal(commands.length,1);assert.equal(commands[0][1],'poker_app:garage:stats:ID2');return [JSON.stringify({best:1234,runs:2,chips:10})];});assert.equal(d.friends.length,1);assert.equal(d.friends[0].trophy.prize,250000);assert.equal(d.friends[0].best,1234);assert.equal(d.friends[0].avatar,null);});
test('friend service failure stays unavailable rather than replacing saved selection',async()=>{const fs=require('fs'),vm=require('vm'),path=require('path'),{createRequire}=require('module'),file=path.resolve('lib/player-lounge.js'),base=createRequire(file),module={exports:{}};vm.runInNewContext(fs.readFileSync(file,'utf8'),{module,require:id=>id==='./api-handlers/friends'?{readNewsFriends:async()=>{throw Error('offline');}}:base(id)});const d=await module.exports.read('ID1',['ID2'],()=>{throw Error('not reached');});assert.equal(d.available,false);assert.equal(module.exports.view({loungeSeats:['ID2',null,null,null,null]},d,true).editable,false);});
