'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createRequire}=require('node:module');
const H=require('../lib/player-hall');
const profile={accountId:'ID1',nick:'Waaaarr',bound:true,name:'Игрок'},stats={first:5,heroes:2,total:1000001,big50:1,big100:1};
const rows=[{tournamentId:'t1',tournament:'Турнир',date:'2026-10-01T12:00:00',nick:'Waaar',place:1,reward:1200},{tournamentId:'t1',tournament:'Турнир',date:'2026-10-01T12:00:00',nick:'Друг',place:2,reward:600}];
test('hall uses verified nickname aliases and preserves exact tournament results and excludes memories',()=>{const list=H.catalog(profile,[{userId:'ID2',nick:'Друг'}],rows,stats,[]);assert.equal(list.filter(i=>i.kind==='cups').length,1);assert.equal(list.filter(i=>i.kind==='memories').length,0);assert.equal(list.find(i=>i.kind==='cups').history.results[0].reward,1200);assert.equal(H.catalog({...profile,bound:false},[],rows,stats,[]).length,0);});
test('server rejects unearned awards, duplicates, locked rooms and more than five trophies',()=>{const items=H.catalog(profile,[],rows,stats,[]);const good={featured:[items[0].id],theme:'walnut',goal:'wins'};assert.deepEqual(H.selection(good,items,stats),good);assert.throws(()=>H.selection({...good,featured:['forged']},items,stats),/не получена/);assert.throws(()=>H.selection({...good,featured:Array(6).fill(items[0].id)},items,stats),/пяти/);assert.throws(()=>H.selection({...good,theme:'midnight'},items,{first:1}),/не открыто/);assert.throws(()=>H.selection({...good,goal:'profit'},items,stats),/цель/);});
test('earned season wall is based on archived summer, excluding September and October',()=>{const seasons=require('../lib/player-hall-seasons.json');assert.ok(Object.values(seasons).flat().length>0);assert.ok(Object.values(seasons).flat().every(i=>['winter','spring','summer'].includes(i.season)&&i.place>0&&[1,2].includes(i.league)));const summer=seasons['покерманки'].find(i=>i.season==='summer'&&i.league===1);assert.equal(summer.place,2);assert.equal(seasons.waaar.find(i=>i.season==='summer'&&i.league===1).place,1);});
function mock(file,stubs){const full=path.resolve(__dirname,'..',file),req=createRequire(full),module={exports:{}};vm.runInNewContext(fs.readFileSync(full,'utf8'),{module,exports:module.exports,require:id=>Object.hasOwn(stubs,id)?stubs[id]:req(id),console,process,Map,Set,Date});return module.exports;}
test('save is always scoped to authenticated user, public target cannot edit another room',async()=>{let target;const handler=mock('lib/api-handlers/player-hall.js',{'../club-social':{context:async()=>({accountId:'ID1',body:{action:'save',targetId:'ID2'}})},'../account-id':{resolveAccountId:async()=>{throw Error('not allowed');}},'../player-hall':{save:async id=>{target=id;return {};}}});const res={status(n){this.code=n;return this;},json(d){this.body=d;return this;}};await handler({},res);assert.equal(target,'ID1');assert.equal(res.code,200);});
test('memory survives a rolling result feed; conflicting version and CAS cannot overwrite room',async()=>{let raw=JSON.stringify({version:3,nick:'waaar',items:[{id:'saved',kind:'cups',title:'Сохранённый кубок'}],featured:['saved']}),collision=false;const hall=mock('lib/player-hall.js',{'./club-social':{memberProfile:async()=>profile,redis:async cmds=>cmds.map(c=>c[0]==='GET'?raw:c[0]==='SMEMBERS'?[]:c[0]==='EVAL'?(collision?0:(raw=c[5],1)):null)},'./friend-tournament-results.json':[],'./profile-achievement-catalog.json':{waaar:stats},'./player-hall-seasons.json':{}});assert.ok((await hall.read('ID1',true)).items.some(i=>i.id==='saved'));await assert.rejects(()=>hall.save('ID1',{version:2}),/другой вкладке/);collision=true;await assert.rejects(()=>hall.save('ID1',{version:3,featured:['saved'],theme:'walnut',goal:'wins'}),/изменился/);collision=false;const saved=await hall.save('ID1',{version:3,featured:['saved'],theme:'walnut',goal:'wins'});assert.equal(saved.version,4);});

test('achievement progress includes locked awards with real counters',()=>{const progress=H.achievementProgress({first:0,total:250000});assert.equal(progress.length,5);assert.equal(progress.find(a=>a.id==='millionaire').value,250000);assert.equal(progress.find(a=>a.id==='millionaire').unlocked,false);assert.equal(H.achievementProgress({first:1})[0].unlocked,true);});

test('two shelves allow five earned awards each and preserve empty positions',()=>{const items=[...Array.from({length:6},(_,n)=>({id:'c'+n,kind:'cups'})),...Array.from({length:5},(_,n)=>({id:'a'+n,kind:'achievements'}))];const shelves={cups:['c0','c1','c2','c3','c4'],achievements:['a0','a1','a2','a3','a4']};const good={featured:[...shelves.cups,...shelves.achievements],shelves,theme:'walnut',goal:'wins'};assert.deepEqual(H.selection(good,items,stats),good);assert.throws(()=>H.selection({...good,featured:[...good.featured,'c5']},items,stats),/пяти/);assert.throws(()=>H.selection({...good,shelves:{...shelves,achievements:['c0',null,null,null,null]}},items,stats),/Неверные/);const sparse={...good,featured:['c0','a0'],shelves:{cups:[null,'c0',null,null,null],achievements:[null,null,null,'a0',null]}};assert.deepEqual(H.selection(sparse,items,stats),sparse);});
