'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const H=require('../lib/profile-hero'),L=require('../lib/hero-lessons'),C=require('../hero-catalog');
const request=(action,extra={})=>({action,requestId:'test-request-00000001',...extra});
function train(s,level,skill){const q=L.lesson(skill,s.skills[skill]||0);return H.mutate(s,level,request('train',{skill,lessonId:q.id,answer:q.answer}));}
test('hero starts with empty equipment and earned level points',()=>{const h=H.view(H.fresh(),71);assert.equal(h.points,70);assert.equal(h.chests,71);assert.deepEqual(h.equippedItems,[]);assert.deepEqual(h.inventory,[]);assert.equal(h.lessons.strike.answer,undefined);});
test('learning requires correct answer, available points and prerequisites',()=>{assert.throws(()=>train(H.fresh(),1,'strike'),/Нет свободных/);assert.throws(()=>train(H.fresh(),20,'tempo'),/предыдущий/);assert.throws(()=>H.mutate(H.fresh(),2,request('train',{skill:'strike',lessonId:'strike:0',answer:2})),/25%/);let s=H.fresh();for(let i=0;i<5;i++)s=train(s,25,'strike');s=train(s,25,'tempo');assert.equal(s.skills.tempo,1);assert.equal(s.practice,6);const reset=H.mutate(s,25,request('reset'));assert.equal(H.view(reset,25).points,24);assert.equal(reset.practice,6);});
test('skill cap, unknown actions and ownership are enforced',()=>{let s=H.fresh();for(let i=0;i<15;i++)s=train(s,100,'strike');assert.throws(()=>train(s,100,'strike'),/максимума/);assert.throws(()=>H.mutate(s,100,request('equip',{item:'someone-else'})),/не найден/);assert.throws(()=>H.mutate(s,100,request('mint')),/Неизвестное/);});
test('level loot cannot be claimed twice; cannot salvage worn equipment',()=>{let s=H.mutate(H.fresh(),1,request('chest'),0,[0,0,0]);assert.equal(s.inventory.length,1);assert.throws(()=>H.mutate(s,1,request('chest')),/уже получены/);s=H.mutate(s,1,request('equip',{item:s.inventory[0].id}));assert.equal(H.view(s,1).equippedItems.length,1);assert.throws(()=>H.mutate(s,1,request('salvage',{item:s.inventory[0].id})),/снимите/);s=H.mutate(s,1,request('unequip',{slot:'head'}));s=H.mutate(s,1,request('salvage',{item:s.inventory[0].id}));assert.equal(s.dust,1);assert.equal(s.inventory.length,0);});
test('daily training requires correct answer and resets at Moscow midnight',()=>{const now=Date.parse('2026-09-10T20:59:00Z'),index=Math.floor((now+10800000)/86400000),q=L.lesson('strike',index);let s=H.mutate(H.fresh(),1,request('adventure',{route:'trail',lessonId:q.id,answer:q.answer}),now);assert.equal(H.view(s,1,true,now).adventureAvailable,false);assert.equal(H.view(s,1,true,now+60001).adventureAvailable,true);assert.throws(()=>H.mutate(s,1,request('adventure',{route:'trail'}),now),/уже забрали/);assert.throws(()=>H.mutate(H.fresh(),1,request('adventure',{route:'citadel'}),now),/техники/);});
test('crafting and public response do not leak private inventory',()=>{let s=H.fresh();s.dust=20;s=H.mutate(s,10,request('craft',{slot:'body'}),0,[0,0,0]);assert.equal(s.inventory[0].slot,'body');assert.equal(s.inventory[0].rarity,1);assert.equal(s.dust,0);const pub=H.view(s,10,false);assert.equal(pub.inventory,undefined);assert.equal(pub.lessons,undefined);assert.equal(pub.chests,undefined);});
test('every skill has useful answer and explanation',()=>{for(const skill of C.skills){for(let n=0;n<2;n++){const l=L.lesson(skill.id,n);assert.ok(l.question.length>30);assert.ok(l.explanation.length>40);assert.ok(l.choices[l.answer]);}}});
test('CAS rejects concurrent rewards and repeated request is idempotent',async()=>{let saved=null;const redis=async commands=>commands.map(c=>{if(c[0]==='GET')return saved;if(c[0]==='HGET')return null;if(c[0]==='EVAL'){if((saved||'')!==c[4])return 0;saved=c[5];return 1;}throw Error('unexpected');});const filename=path.resolve('lib/profile-hero.js');const ctx={module:{exports:{}},require:id=>id==='./club-social'?{redis}:require(require.resolve(id,{paths:[path.dirname(filename)]})),Date,console};vm.runInNewContext(fs.readFileSync(filename,'utf8'),ctx);const api=ctx.module.exports;const b=request('chest',{version:0});const results=await Promise.allSettled([api.updateHero('ID1',b),api.updateHero('ID1',{...b,requestId:'other-request-000001'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const done=await api.updateHero('ID1',b);assert.equal(done.inventory.length,1);assert.equal(JSON.parse(saved).claimedLevel,1);});
