import * as T from '../../vendor/three/three.module.min.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function makeModel(scene,look){
 const G=window.PokerGarage,car=new T.Group();scene.add(car);const mats={};
 const mat=(name,color,metalness=.1,roughness=.5)=>mats[name]=new T.MeshStandardMaterial({color,metalness,roughness});
 const paint=mat('paint',G.item('paint',look.paint).color,.65,.24),felt=mat('felt',G.item('paint',look.paint).color,0,.92),gold=mat('gold','#d6a744',.92,.18),rubber=mat('rubber','#14181c',.08,.82),rim=mat('rim',G.item('wheels',look.wheels).color,.84,.23),black=mat('black','#10181b',.25,.36),seat=mat('seat','#10221c',.1,.72),light=mat('light',G.item('light',look.light).color,.25,.22);light.emissive=new T.Color(light.color);light.emissiveIntensity=.85;
 function mesh(g,m,x=0,y=0,z=0,parent=car){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 const box=(w,h,d,m,x,y,z)=>mesh(new T.BoxGeometry(w,h,d),m,x,y,z);
 const sphere=(r,m,x,y,z)=>mesh(new T.SphereGeometry(r,24,16),m,x,y,z);
 function cylinder(r,h,m,x,y,z,axis='y'){const o=mesh(new T.CylinderGeometry(r,r,h,48),m,x,y,z);if(axis==='z')o.rotation.x=Math.PI/2;if(axis==='x')o.rotation.z=Math.PI/2;return o;}
 function torus(r,t,m,x,y,z,axis='z'){const o=mesh(new T.TorusGeometry(r,t,12,64),m,x,y,z);if(axis==='y')o.rotation.x=Math.PI/2;if(axis==='x')o.rotation.y=Math.PI/2;return o;}
 function rounded(w,d,h,r,m,y,hollow=false){const s=new T.Shape(),x=-w/2,z=-d/2;s.moveTo(x+r,z);s.lineTo(x+w-r,z);s.quadraticCurveTo(x+w,z,x+w,z+r);s.lineTo(x+w,z+d-r);s.quadraticCurveTo(x+w,z+d,x+w-r,z+d);s.lineTo(x+r,z+d);s.quadraticCurveTo(x,z+d,x,z+d-r);s.lineTo(x,z+r);s.quadraticCurveTo(x,z,x+r,z);if(hollow){const hole=new T.Path();hole.moveTo(-1.48,-.7);hole.lineTo(-1.48,.7);hole.quadraticCurveTo(-1.48,.8,-1.3,.8);hole.lineTo(.45,.8);hole.quadraticCurveTo(.65,.8,.65,.6);hole.lineTo(.65,-.6);hole.quadraticCurveTo(.65,-.8,.45,-.8);hole.lineTo(-1.3,-.8);hole.quadraticCurveTo(-1.48,-.8,-1.48,-.7);s.holes.push(hole);}const o=mesh(new T.ExtrudeGeometry(s,{depth:h,bevelEnabled:true,bevelSize:.035,bevelThickness:.025,bevelSegments:3,curveSegments:24}),m,0,y,0);o.rotation.x=-Math.PI/2;return o;}
 rounded(4.8,2.5,.51,.75,paint,.72,true);rounded(4.9,2.62,.07,.8,gold,1.23,true);rounded(5,2.7,.14,.84,black,1.31,true);rounded(4.68,2.4,.035,.73,gold,1.44,true);rounded(4.52,2.24,.025,.66,felt,1.48,true);rounded(4.7,2.5,.06,.75,gold,.68);
 // A padded continuous rail, rather than the flat slab used by the prototype.
 const railPoints=[];for(let corner=0;corner<4;corner++){const cx=corner===0||corner===3?1.66:-1.66,cz=corner<2?.52:-.52;for(let n=0;n<=16;n++){const angle=corner*Math.PI/2+n*Math.PI/32;railPoints.push(new T.Vector3(cx+Math.cos(angle)*.78,1.47,cz+Math.sin(angle)*.78));}}
 mesh(new T.TubeGeometry(new T.CatmullRomCurve3(railPoints,true,'centripetal'),160,.105,12,true),black);
 // Inner upholstered walls visibly descend into the driving well.
 for(const z of [-.78,.78])box(1.92,.38,.055,paint,-.43,1.27,z);
 for(const x of [-1.46,.64])box(.055,.38,1.5,paint,x,1.27,0);
 // Felt weave and printed betting oval are actual textures on the horizontal table.
 const cloth=document.createElement('canvas');cloth.width=512;cloth.height=256;const cc=cloth.getContext('2d');cc.fillStyle='#787878';cc.fillRect(0,0,512,256);let seed=7;for(let i=0;i<14000;i++){seed=(seed*1664525+1013904223)>>>0;cc.fillStyle='rgba(0,0,0,.035)';cc.fillRect(seed%512,(seed>>>10)%256,1,1);}cc.strokeStyle='#b5a16c';cc.lineWidth=2;cc.beginPath();cc.ellipse(256,128,208,94,0,0,Math.PI*2);cc.stroke();const clothTex=new T.CanvasTexture(cloth);clothTex.colorSpace=T.SRGBColorSpace;felt.map=clothTex;
 const classicWheelDetails=[];
 // Four separate tires, hubs, spokes and tread bands.
 for(const x of [-1.66,1.66])for(const z of [-1.39,1.39]){cylinder(.69,.43,rubber,x,.7,z,'z');const out=z+Math.sign(z)*.235;cylinder(.49,.055,rim,x,.7,out,'z');cylinder(.37,.06,black,x,.7,out+Math.sign(z)*.035,'z');torus(.44,.035,gold,x,.7,out+Math.sign(z)*.06);cylinder(.16,.09,rim,x,.7,out+Math.sign(z)*.08,'z');classicWheelDetails.push(cylinder(.31,.02,black,x,.7,out+Math.sign(z)*.09,'z'),torus(.32,.022,gold,x,.7,out+Math.sign(z)*.105));for(let n=0;n<8;n++){const a=n*Math.PI/4,sp=box(.055,.31,.045,rim,x+Math.sin(a)*.27,.7+Math.cos(a)*.27,out+Math.sign(z)*.065);sp.rotation.z=-a;}for(let n=0;n<5;n++)torus(.685,.008,black,x,.7,z+(n-2)*.075);}
 function spade(size,m,x,y,z,flip=false){const s=new T.Shape();s.moveTo(0,.5);s.bezierCurveTo(-.12,.28,-.48,.12,-.3,-.1);s.bezierCurveTo(-.2,-.23,-.05,-.17,0,-.06);s.bezierCurveTo(.05,-.17,.2,-.23,.3,-.1);s.bezierCurveTo(.48,.12,.12,.28,0,.5);s.moveTo(-.12,-.3);s.lineTo(0,-.06);s.lineTo(.12,-.3);s.closePath();const o=mesh(new T.ShapeGeometry(s),m,x,y,z);o.scale.setScalar(size);if(flip)o.rotation.y=Math.PI;return o;}
 for(const z of [-1.78,1.78])for(const x of [-1.66,1.66])spade(.7,gold,x,.68,z,z<0);
 for(const z of [-1.29,1.29])spade(.6,gold,-1.1,1.03,z,z<0);
 // Gold cup holders and chip stacks.
 for(const x of [-1.78,-.2,1.65])for(const z of [-1,1]){cylinder(.12,.025,black,x,1.51,z);torus(.14,.028,gold,x,1.54,z,'y');}
 const chipMats=['#ac2940','#e8e3cf','#285bb8'].map(c=>new T.MeshStandardMaterial({color:c,roughness:.65}));for(const [x,z,n,count] of [[-1.45,.94,0,6],[-1.12,.94,2,5],[.0,.94,1,4],[.65,-.94,0,4],[1.52,.65,2,6],[1.85,-.6,0,5]])for(let j=0;j<count;j++){cylinder(.105,.038,chipMats[n],x,1.55+j*.043,z);for(let k=0;k<6;k++){const a=k*Math.PI/3;const dash=box(.035,.02,.018,chipMats[1],x+Math.cos(a)*.101,1.55+j*.043,z+Math.sin(a)*.101);dash.rotation.y=-a;}}
 // Cockpit with bucket seat and an angled steering column.
 rounded(1.9,1.45,.07,.25,paint,1.03);box(.65,.1,.62,seat,-.65,1.09,0);const back=box(.12,.30,.62,seat,-1.12,1.24,0);back.rotation.z=-.15;
 const col=cylinder(.055,.65,gold,.6,1.86,0,'x');col.rotation.z=-.65;
 const wheel=new T.Group();wheel.position.set(.83,2.08,0);wheel.rotation.z=-.4;car.add(wheel);const ring=new T.Mesh(new T.TorusGeometry(.32,.045,12,48),black);ring.rotation.y=Math.PI/2;wheel.add(ring);const hub=new T.Mesh(new T.CylinderGeometry(.1,.1,.08,24),gold);hub.rotation.z=Math.PI/2;wheel.add(hub);for(let i=0;i<3;i++){const o=new T.Mesh(new T.BoxGeometry(.04,.25,.035),gold);const a=i*Math.PI*2/3;o.position.set(0,Math.cos(a)*.15,Math.sin(a)*.15);o.rotation.x=a;wheel.add(o);}
 // Rear turbine, metallic housing, luminous fan and angled blades.
 cylinder(.7,.65,gold,-1.55,2.04,0,'z');cylinder(.61,.68,black,-1.55,2.04,0,'z');
 for(const sign of [-1,1]){const z=sign*.36;torus(.63,.055,gold,-1.55,2.04,z);torus(.56,.018,light,-1.55,2.04,z+sign*.02);cylinder(.17,.08,gold,-1.55,2.04,z+sign*.08,'z');cylinder(.13,.09,black,-1.55,2.04,z+sign*.1,'z');for(let n=0;n<16;n++){const a=n*Math.PI/8;const curve=new T.CatmullRomCurve3([new T.Vector3(-1.55+Math.sin(a)*.2,2.04+Math.cos(a)*.2,z),new T.Vector3(-1.55+Math.sin(a+.25)*.4,2.04+Math.cos(a+.25)*.4,z+sign*.025),new T.Vector3(-1.55+Math.sin(a+.4)*.56,2.04+Math.cos(a+.4)*.56,z)]);mesh(new T.TubeGeometry(curve,12,.012,5,false),light);const vertices=[],indices=[];for(let j=0;j<=12;j++){const t=j/12,r=.20+t*.36,angle=a+.4*t;for(const offset of [-.12,.12])vertices.push(-1.55+Math.sin(angle+offset)*r,2.04+Math.cos(angle+offset)*r,z+sign*.005);}for(let j=0;j<12;j++){const k=j*2;indices.push(k,k+1,k+2,k+1,k+3,k+2);}const blade=new T.BufferGeometry();blade.setAttribute('position',new T.Float32BufferAttribute(vertices,3));blade.setIndex(indices);blade.computeVertexNormals();const bladeMat=new T.MeshStandardMaterial({color:'#247c8b',metalness:.8,roughness:.22,side:T.DoubleSide});mesh(blade,bladeMat);}}
 for(let n=0;n<10;n++){const a=n*Math.PI/5;const vent=box(.16,.055,.24,black,-1.55+Math.cos(a)*.7,2.04+Math.sin(a)*.7,0);vent.rotation.z=a;}
 for(const z of [-.83,.83])for(const y of [.91,1.08]){const led=box(.035,.045,.39,light,2.49,y,z);led.rotation.y=z>0?-.12:.12;}
 for(const z of [-1.12,1.12]){const curve=new T.CatmullRomCurve3([new T.Vector3(2.18,.76,z),new T.Vector3(2.43,.85,z),new T.Vector3(2.48,1.1,z),new T.Vector3(2.30,1.28,z)]);mesh(new T.TubeGeometry(curve,24,.055,10,false),gold);}
 const steeringSpade=spade(.23,gold,0,0,0);wheel.add(steeringSpade);steeringSpade.position.set(.07,0,-.015);steeringSpade.rotation.y=Math.PI/2;
 // Cards and readable club plaques on both sides.
 const textures=[];function label(text,color,bg,w=512,h=128){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold '+Math.min(w*.38,h*.42)+'px Georgia';ctx.fillText(text,w/2,h/2);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;textures.push(t);return t;}
 for(const z of [-1.267,1.267]){const border=box(1.55,.43,.035,gold,.15,.99,z);const plaque=mesh(new T.PlaneGeometry(1.45,.34),new T.MeshStandardMaterial({map:label('TWO ACES','#e5c77e','#101b1c'),roughness:.5}),.15,.99,z+Math.sign(z)*.022);if(z<0)plaque.rotation.y=Math.PI;}
 for(let i=0;i<2;i++){const c=mesh(new T.PlaneGeometry(.38,.55),new T.MeshStandardMaterial({map:label(i?'A ♥':'A ♠',i?'#a62635':'#172026','#f4efda',128,192),roughness:.9}),1.23+i*.27,1.57,-.38+i*.12);c.rotation.x=-Math.PI/2;c.rotation.z=i*.2;}
 const numberMat=new T.MeshStandardMaterial({map:new T.CanvasTexture(G.plateCanvas(look)),roughness:.65});const num=mesh(new T.PlaneGeometry(.85,.498),numberMat,2.49,.97,0);num.rotation.y=Math.PI/2;const rearPlate=mesh(new T.PlaneGeometry(.85,.498),numberMat,-2.49,.87,0);rearPlate.rotation.y=-Math.PI/2;
 // Equipment appears on the empty driver's seat; it remains separate from body paint.
 const helmet=new T.Group();helmet.position.set(-.58,1.84,0);car.add(helmet);const shell=new T.Mesh(new T.SphereGeometry(.23,32,20),new T.MeshStandardMaterial({color:G.item('helmet',look.helmet).color,metalness:.35,roughness:.26}));helmet.add(shell);const visor=new T.Mesh(new T.SphereGeometry(.235,24,16,0,Math.PI,.7,1.15),black);visor.rotation.y=Math.PI/2;helmet.add(visor);
 function update(v){classicWheelDetails.forEach(o=>o.visible=v.wheels==='classic');paint.color.set(G.item('paint',v.paint).color);felt.color.copy(paint.color);rim.color.set(G.item('wheels',v.wheels).color);light.color.set(G.item('light',v.light).color);light.emissive.copy(light.color);helmet.visible=v.helmet!=='none';shell.material.color.set(G.item('helmet',v.helmet).color);if(numberMat.userData.number!==v.number+v.region){numberMat.map?.dispose();numberMat.map=new T.CanvasTexture(G.plateCanvas(v));numberMat.userData.number=v.number+v.region;numberMat.needsUpdate=true;}}
 update(look);return {car,update};
}
window.pokerCreateGarage3D=function(host,look,state={}){
 let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch(_){host.textContent='3D-просмотр недоступен на этом устройстве';return null;}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Объёмная машина: потяните, чтобы повернуть');renderer.domElement.setAttribute('role','img');
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(35,1,.1,60);scene.add(new T.HemisphereLight('#c6d9ef','#44311e',1.25));
 for(const [color,intensity,x,y,z] of [['#fff0d0',3,3,6,4],['#9dcfff',1.5,-4,3,-3],['#ffffff',1.5,0,5,-4]]){const l=new T.DirectionalLight(color,intensity);l.position.set(x,y,z);l.castShadow=true;l.shadow.mapSize.set(1024,1024);l.shadow.camera.left=-5;l.shadow.camera.right=5;l.shadow.camera.top=5;l.shadow.camera.bottom=-5;scene.add(l);}
 const studio=new T.Scene();studio.background=new T.Color('#30343c');for(const [x,y,z,w,h,d] of [[0,5,0,8,.1,8],[4,2,0,.1,4,5],[-4,2,-2,.1,4,4]]){const p=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshBasicMaterial({color:'#ffffff'}));p.position.set(x,y,z);studio.add(p);}const pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(studio,.05);scene.environment=env.texture;studio.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});pmrem.dispose();
 const ground=new T.Mesh(new T.PlaneGeometry(30,30),new T.ShadowMaterial({opacity:.34}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const model=makeModel(scene,look);
 state.yaw??=1.02;state.pitch??=.38;state.manual??=window.matchMedia('(prefers-reduced-motion: reduce)').matches;let disposed=false,drag=null,raf=0,last=0;
 const fit=()=>{const w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}};const resize=new ResizeObserver(fit);resize.observe(host);fit();
 const down=e=>{if(e.button&&e.button!==0)return;state.manual=true;drag={id:e.pointerId,x:e.clientX,y:e.clientY};host.setPointerCapture(e.pointerId);e.preventDefault();};const move=e=>{if(!drag||drag.id!==e.pointerId)return;state.yaw-=(e.clientX-drag.x)*.011;state.pitch=clamp(state.pitch+(e.clientY-drag.y)*.009,-.24,1.35);drag.x=e.clientX;drag.y=e.clientY;e.preventDefault();};const up=e=>{if(drag&&drag.id===e.pointerId){drag=null;if(host.hasPointerCapture(e.pointerId))host.releasePointerCapture(e.pointerId);}};
 const key=e=>{const turns={ArrowLeft:[.12,0],ArrowRight:[-.12,0],ArrowUp:[0,.09],ArrowDown:[0,-.09]};if(!turns[e.key])return;state.manual=true;state.yaw+=turns[e.key][0];state.pitch=clamp(state.pitch+turns[e.key][1],-.24,1.35);e.preventDefault();};host.addEventListener('keydown',key);host.addEventListener('pointerdown',down);host.addEventListener('pointermove',move);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',up);host.addEventListener('lostpointercapture',up);
 function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);resize.disconnect();host.removeEventListener('keydown',key);host.removeEventListener('pointerdown',down);host.removeEventListener('pointermove',move);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',up);host.removeEventListener('lostpointercapture',up);const textures=new Set(),materials=new Set(),geometries=new Set();scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)materials.add(o.material);});materials.forEach(m=>{if(m.map)textures.add(m.map);m.dispose();});textures.forEach(t=>t.dispose());geometries.forEach(g=>g.dispose());env.dispose();renderer.dispose();renderer.domElement.remove();}
 function tick(time){if(disposed)return;if(!host.isConnected||(host.closest('dialog')&&!host.closest('dialog').open)){dispose();return;}const dt=last?Math.min(.05,(time-last)/1000):0;last=time;if(!document.hidden&&host.getBoundingClientRect().bottom>0){if(!state.manual)state.yaw+=dt*.13;const distance=8.4;camera.position.set(Math.sin(state.yaw)*Math.cos(state.pitch)*distance,1.15+Math.sin(state.pitch)*distance,Math.cos(state.yaw)*Math.cos(state.pitch)*distance);camera.lookAt(0,1.2,0);renderer.render(scene,camera);host.dataset.yaw=state.yaw.toFixed(4);host.dataset.pitch=state.pitch.toFixed(4);host.dataset.manual=String(state.manual);}raf=requestAnimationFrame(tick);}
 raf=requestAnimationFrame(tick);return {update:model.update,dispose,state};
};
